### ISSUE TITLE
Shared-Cache mode?

### ISSUE THREAD

**Issue by zzak** [sparklemotion/sqlite3-ruby#110]
Is there support for anything [like this](http://www.sqlite.org/sharedcache.html) in the sqlite3 gem?

**Comment by jmccaffrey** [comment]
In case anyone is wondering about the performance implications of the shared_cache setting, and whether it would solve their issues: http://manski.net/2012/10/sqlite-performance/

**Comment by jimflood** [comment]
You can now use the flags parameter to Database.new to pass SQLITE_OPEN_SHAREDCACHE and try it out.
