### ISSUE TITLE
Database#execute returns no rows if multiple SQL statements in one command

### ISSUE THREAD

**Issue by steveg-h** [sparklemotion/sqlite3-ruby#111]
Detailed description

Hi,
I'm using sqlite3-1.3.8 under ruby2.0.0-p195

If you put multiple SQL statements into a single Database#execute statement, then the result set returned is empty.
This does not match the behaviour on the Sqlite3 command line.

db=SQLite3::Database.new('test.db')
db.execute 'CREATE TABLE IF NOT EXISTS test( id INTEGER, val TEXT)'

row=db.execute "INSERT INTO test(id, val) VALUES (1, 'foo'); SELECT last_insert_rowid() AS id"
pp row  # => []

row=db.execute "SELECT last_insert_rowid() AS id"
pp row  # => [[1]]

I'm not sure if this is a feature, a bug in the ruby code or the underlying sqlite3 C API.

Cheers

Steve

**Comment by penguinpowernz** [comment]
Pretty sure you should use the `execute_batch` method for that dude....

**Comment by tenderlove** [comment]
`execute` only supports one statement at a time.  If you need to do more statements, then use `execute_batch` or just call `execute` more than once.
