### ISSUE TITLE
Encoding issues on mips, powerpc, s390x

### ISSUE THREAD

**Issue by zeha** [sparklemotion/sqlite3-ruby#128]
Hi there,

while building the Debian packages for 1.9.3, the tests found some encoding errors on the mips, powerpc and s390x architectures.

On mips & powerpc:
```
  1) Failure:
SQLite3::TestEncoding#test_select_encoding_on_utf_16 [/«PKGBUILDDIR»/test/test_encoding.rb:23]:
Expected: 1
  Actual: 0
```

On s390x:
```
  1) Failure:
SQLite3::TestEncoding#test_insert_encoding [/«PKGBUILDDIR»/test/test_encoding.rb:42]:
Expected: "foo"
  Actual: "\u6600\u6F00\u6F00"
```

I hoped you could shed some light on these test failures.

Detailed build logs can be found at:
https://buildd.debian.org/status/fetch.php?pkg=ruby-sqlite3&arch=mips&ver=1.3.9-1&stamp=1396866955
https://buildd.debian.org/status/fetch.php?pkg=ruby-sqlite3&arch=powerpc&ver=1.3.9-1&stamp=1396865677
https://buildd.debian.org/status/fetch.php?pkg=ruby-sqlite3&arch=s390x&ver=1.3.9-1&stamp=1396865788

(All of this happens under ruby2.0.)

**Comment by tenderlove** [comment]
I've applied this patch on master.  Thanks!
