### ISSUE TITLE
SQLite3::NotADatabaseException/SQLite3::CorruptException with forked processes/inserts

### ISSUE THREAD

**Issue by garysweaver** [sparklemotion/sqlite3-ruby#129]
In https://github.com/travis-ci/travis-ci/issues/1334, I noticed that a SQLite file-based DB seemed to get corrupted in tests in Travis CI when multiple processes were doing inserts. I had asked on the SQLite users list about it, learned about how SQLite relied on POSIX advisory locks to work correctly and that network file systems could be to blame if there are problems. Since Travis's hosting provider (Bluebox, I think) might be able to assist, I asked if the Travis CI team would ask them about it. Here is an example of that error (in sqlite 1.3.7):

```
/home/travis/.rvm/gems/ruby-2.0.0-p451/gems/sqlite3-1.3.7/lib/sqlite3/statement.rb:108:in `step': SQLite3::NotADatabaseException: file is encrypted or is not a database: INSERT INTO "foos" ("cname") VALUES (?) (ActiveRecord::StatementInvalid)

from /home/travis/.rvm/gems/ruby-2.0.0-p451/gems/sqlite3-1.3.7/lib/sqlite3/statement.rb:108:in `block in each'
...
```

The Travis CI team just followed up and said they'd ask, so I wanted to try to simplify the reproduction of the issue in [travis_ci_sqlite_write_concurrency_tests](https://github.com/garysweaver/travis_ci_sqlite_write_concurrency_tests/). I haven't yet succeeded in producing exactly the same error. However, in trying to reproduce the error from [otw](https://github.com/garysweaver/otw), I found that when travis_ci_sqlite_write_concurrency_tests is running in Ruby 2.0.0p451 in Travis CI, there are some `database disk image is malformed (SQLite3::CorruptException)` in the [log](https://travis-ci.org/garysweaver/travis_ci_sqlite_write_concurrency_tests/jobs/24503254), and that same thing does not appear to happen in Ruby 2.1 or 1.9.3, which I thought was strange, and possibly something that would be of interest in the sqlite3-ruby project. (Note: I have the tests let "disk I/O error" messages pass, because those were happening on my Mac, and it wasn't a corruption error, but it doesn't necessarily prove it wouldn't have been corrupted.)

I don't think that the sqlite gem is necessarily doing anything wrong, but thought maybe you could shine light on why might be causing the otw tests to fail the way they do, and why SQLite3::CorruptException only happens in Ruby 2.0.0 but not 1.9.3 or 2.1.

I could just set up the same situation (use of Rails, etc.) in travis_ci_sqlite_write_concurrency_tests that I do in the otw tests, but I had assumed that the problem was related to SQLite concurrent write to file DB incompatibility with the hosting environment, so I thought I could just use the sqlite gem directly and reduce dependencies to a minimum to reproduce.

Thanks, and if you don't have time, please feel free to close. Just hoping that maybe someone could shine some light on it.

**Comment by tenderlove** [comment]
It looks like you're forking and not reopening the database inside the forks.  This will share the file descriptor between processes.  I don't think SQLite3 is equipped to handle that (since it would mean implementing some sort of IPC).  I believe SQLite does rely on POSIX advisory locks, but that is only going to work well if the database file descriptor *isn't* shared between processes.  Can you try reopening the database in each child process?  I think that should fix the issue.

**Comment by tenderlove** [comment]
Closing this issue because it seems stale.  Please comment if it's still a problem.
