### ISSUE TITLE
Support for file::memory URI?

### ISSUE THREAD

**Issue by cambridgemike** [sparklemotion/sqlite3-ruby#145]
I'm trying to use an in-memory database that is shared across threads. The [SQLite docs](https://www.sqlite.org/inmemorydb.html) say this can be done using the following as the filename "file::memory:?cache=shared". However, when I try this with the ruby gem it just creates a file with that name

**Comment by grosser** [comment]
do you have a link for the AR issue or a solution @cambridgemike ?

**Comment by grosser** [comment]
AR issue is https://github.com/rails/rails/issues/8805
and has no solution, neither has the stackoverflow it links 😞
