### ISSUE TITLE
JRuby + sqlite3_native.so.1 - Invalid Char \177

### ISSUE THREAD

**Issue by mistergibson** [sparklemotion/sqlite3-ruby#148]
require 'sqlite3'
SyntaxError: /opt/jruby-1.7.18/lib/ruby/gems/shared/gems/sqlite3-1.3.10/lib/sqlite3/sqlite3_native.so:1: Invalid char `\177' ('') in expression
ELF>À.@Ð@8@,~,~ hh h @   ÐÐÈÈÈ$$PåtdÔqÔqÔqddQåtdRåtdhh h GNU×lM 5ªr(TØ¬¬ý¸|	
                                                        |}$¥½êÓïI{z:&0<êºVtQ¹ñÙqX»ã|ÐS[ê,-¶(IBEÕìB
                                        ³Zã»(.&>_¾	h'@¥*Ê!hZ ÷
         Îi¥ú/¬~<]¿zÈëv0Yb°¸@@P1à»Uý Oÿõìj©Îb	ãÿä¯ÀJ¨ôaÕ[ é¬qDw1Q×÷ìÃ®°+Õ>î2 ÃÈvL"Ô}¸,o½E
                                       :
                                           Xip
                                                rV>
                                                       .FµS
                                                            ÑJ"tXã	h'O	¨ [	p Ý
                &g0c`Ó
                             ôNH	¨ äH¹Ph
                                                               ÌWâ__gmon_start___fini_ITM_deregisterTMCloneTable_ITM_registerTMCloneTable__cxa_finalize_Jv_RegisterClassesrb_fix2intrb_num2intrb_float_new_in_heaprb_cFixnumrb_cFloatrb_cTrueClassrb_cSymbolrb_cNilClassrb_cFalseClasscSqlite3Databasesqlite3_closeruby_xfreeruby_xcallocrb_data_object_allocrb_string_valuerb_str_buf_catrb_check_typerb_scan_argsrb_string_value_ptrrb_check_safe_objrb_hash_newrb_hash_arefsqlite3_open16rb_intern2sqlite3_open_v2rb_sqlite3_raiserb_iv_setrb_block_given_prb_yieldrb_funcallrb_path2classrb_raisesqlite3_total_changesrb_iv_getrb_str_new_cstrrb_block_procsqlite3_tracesqlite3_busy_handlersqlite3_last_insert_rowidrb_ll2inumsqlite3_value_typesqlite3_value_int64sqlite3_value_doublesqlite3_value_textrb_tainted_str_new_cstrsqlite3_value_bytessqlite3_value_blobrb_tainted_str_newrb_eRuntimeErrorsqlite3_result_nullsqlite3_result_int64rb_num2dblsqlite3_result_doublesqlite3_result_textrb_class2namesqlite3_user_datarb_funcall2rb_proc_aritysqlite3_create_functionrb_hash_asetsqlite3_interruptsqlite3_errmsgsqlite3_errcodesqlite3_completesqlite3_changessqlite3_set_authorizersqlite3_busy_timeoutrb_comparator_funcrb_str_newsqlite3_create_collationsqlite3_load_extensionrb_exc_new2sqlite3_freerb_exc_raisesqlite3_enable_load_extensionsqlite3_execsqlite3_get_autocommitinit_sqlite3_databaserb_cObjectmSqlite3rb_define_class_underrb_define_alloc_funcrb_define_methodcSqlite3Backuprb_eArgErrorsqlite3_backup_initsqlite3_backup_stepsqlite3_backup_finishsqlite3_backup_remainingsqlite3_backup_pagecountinit_sqlite3_backuprb_num2llcSqlite3Blobbignum_to_int64sqlite3_libversion_numberInit_sqlite3_nativerb_define_modulerb_cStringsqlite3_initializeinit_sqlite3_statementrb_define_singleton_methodrb_define_constcSqlite3Statementsqlite3_prepare_v2sqlite3_finalizesqlite3_stepsqlite3_column_countrb_ary_new2sqlite3_column_typesqlite3_column_int64rb_ary_pushsqlite3_column_doublesqlite3_column_bytessqlite3_column_textsqlite3_column_blobsqlite3_resetsqlite3_db_handlerb_str_plussqlite3_bind_parameter_indexsqlite3_bind_blobsqlite3_bind_textsqlite3_bind_int64sqlite3_bind_doublesqlite3_bind_nullsqlite3_clear_bindingssqlite3_column_namesqlite3_column_decltypesqlite3_bind_parameter_countsqlite3_column_database_namelibsqlite3.so.0libc.so.6_edata__bss_start_endGLIBC_2.2.5>	ui	`	hp/p0/ X 
                                                                         ` h p x    8   I¨ N° ¸ UÀ XÈ Ð bØ nà pè rð ø {   ( 0 8 @ H PX 	` 
^
	from org/jruby/RubyKernel.java:1071:in `require'
	from /opt/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
	from /opt/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'
	from org/jruby/RubyKernel.java:1071:in `require'
	from /opt/jruby-1.7.18/lib/ruby/gems/shared/gems/sqlite3-1.3.10/lib/sqlite3.rb:6:in `(root)'
	from /opt/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
	from org/jruby/RubyKernel.java:1107:in `eval'
	from /opt/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:135:in `require'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1507:in `loop'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from /usr/bin/jirb:13:in `(root)'

**Comment by tenderlove** [comment]
You're trying to load a shared object with JRuby.  We don't support that.  Please use MRI, or the Java equivalent of sqlite3.
