### ISSUE TITLE
No sqlite3_libversion_number in -lsqlite3 [OS X]

### ISSUE THREAD

**Issue by thislooksfun** [sparklemotion/sqlite3-ruby#152]
Hello! I am trying to install this gem on my Mac (running Yosemite), and every time I try, it gives me the following error:

    ERROR:  Error installing sqlite3:
    ERROR: Failed to build gem native extension.
    
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb --with-opt-dir=/usr/local
    checking for sqlite3.h... yes
    checking for sqlite3_libversion_number() in -lsqlite3... no
    sqlite3 is missing. Try 'port install sqlite3 +universal',
    'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
    and check your shared library search path (the
    location where your sqlite3 shared library is located).
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.
    
    Provided configuration options:
            --with-opt-dir
            --with-opt-include
            --without-opt-include=${opt-dir}/include
            --with-opt-lib
            --without-opt-lib=${opt-dir}/lib
            --with-make-prog
            --without-make-prog
            --srcdir=.
            --curdir
            --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
            --with-sqlite3-dir
            --without-sqlite3-dir
            --with-sqlite3-include
            --without-sqlite3-include=${sqlite3-dir}/include
            --with-sqlite3-lib
            --without-sqlite3-lib=${sqlite3-dir}/
            --with-sqlite3lib
            --without-sqlite3lib
    
    
    Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/sqlite3-1.3.10 for inspection.
    Results logged to /Library/Ruby/Gems/2.0.0/gems/sqlite3-1.3.10/ext/sqlite3/gem_make.out

I have tried every fix I could find on Google, and none of them worked. If you could tell me what I'm doing wrong (even if I'm just being an idiot) that would be great.

Thanks,
-tlf

**Comment by tenderlove** [comment]
Can you find the `mkmf.log` file and the `gem_make.out` file and paste them here?

**Comment by thislooksfun** [comment]
**mkfm.log:**
```
find_header: checking for sqlite3.h... -------------------- yes

"xcrun clang -o conftest -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14 -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/backward -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0 -I. -I/usr/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_SYNC_BUILTINS conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib -L/usr/local/lib -L. -L/usr/local/lib   -arch x86_64 -arch i386   -lruby.2.0.0  -lpthread -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"xcrun clang -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14 -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/backward -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0 -I. -I/usr/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_SYNC_BUILTINS  -arch x86_64 -arch i386  -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <sqlite3.h>
/* end */

--------------------

find_library: checking for sqlite3_libversion_number() in -lsqlite3... -------------------- no

"xcrun clang -o conftest -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14 -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/backward -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0 -I. -I/usr/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_SYNC_BUILTINS conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib -L/usr/local/lib -L. -L/usr/local/lib   -arch x86_64 -arch i386   -lruby.2.0.0 -lsqlite3  -lpthread -ldl -lobjc "
conftest.c:5:57: error: use of undeclared identifier 'sqlite3_libversion_number'
int t(void) { void ((*volatile p)()); p = (void ((*)()))sqlite3_libversion_number; return 0; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int t(void) { void ((*volatile p)()); p = (void ((*)()))sqlite3_libversion_number; return 0; }
 6: int main(int argc, char **argv)
 7: {
 8:   if (argc > 1000000) {
 9:     printf("%p", &t);
10:   }
11: 
12:   return 0;
13: }
/* end */

"xcrun clang -o conftest -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14 -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/backward -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0 -I. -I/usr/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_SYNC_BUILTINS conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib -L/usr/local/lib -L. -L/usr/local/lib   -arch x86_64 -arch i386   -lruby.2.0.0 -lsqlite3  -lpthread -ldl -lobjc "
conftest.c:5:15: warning: implicit declaration of function 'sqlite3_libversion_number' is invalid in C99 [-Wimplicit-function-declaration]
int t(void) { sqlite3_libversion_number(); return 0; }
              ^
1 warning generated.
conftest.c:5:15: warning: implicit declaration of function 'sqlite3_libversion_number' is invalid in C99 [-Wimplicit-function-declaration]
int t(void) { sqlite3_libversion_number(); return 0; }
              ^
1 warning generated.
ld: warning: ignoring file /usr/local/lib/libsqlite3.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libsqlite3.dylib
Undefined symbols for architecture i386:
  "_sqlite3_libversion_number", referenced from:
      _t in conftest-265d8e.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int t(void) { sqlite3_libversion_number(); return 0; }
 6: int main(int argc, char **argv)
 7: {
 8:   if (argc > 1000000) {
 9:     printf("%p", &t);
10:   }
11: 
12:   return 0;
13: }
/* end */

--------------------
```

**gem_make.out:**
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb --with-opt-dir=/usr/local
checking for sqlite3.h... yes
checking for sqlite3_libversion_number() in -lsqlite3... no
sqlite3 is missing. Try 'port install sqlite3 +universal',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--with-sqlite3-dir
	--without-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/
	--with-sqlite3lib
	--without-sqlite3lib
```

**Comment by tenderlove** [comment]
This seems to be the problem:

```
ld: warning: ignoring file /usr/local/lib/libsqlite3.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libsqlite3.dylib
Undefined symbols for architecture i386:
  "_sqlite3_libversion_number", referenced from:
      _t in conftest-265d8e.o
ld: symbol(s) not found for architecture i386
```

How did you install sqlite3?  It looks like you're using the system Ruby along with sqlite3 from brew maybe?

**Comment by thislooksfun** [comment]
I thought I was using the system sqlite3, but I might be wrong...
What would be the easiest way to fix it do you think?

**Comment by tenderlove** [comment]
Well, if you're not using homebrew or something, you can just rm `/usr/local/lib/libsqlite3.dylib`.  I would try to figure out where that file came from though.

**Comment by thislooksfun** [comment]
That worked! I did try installing it through brew at one point, but then I uninstalled it again. I guess not everything got removed though.

**Comment by yeelan0319** [comment]
Thanks @tenderlove. Checking the information in `mkfm.log` made things much clearer. In my case I needed not only to remove `/usr/local/opt/sqlite/lib/libsqlite3.dylib` but also `/usr/local/opt/sqlite/lib/libsqlite3.a` .

**Comment by PeqNP** [comment]
I know this is a bit late, but my issue was that the gem was attempting to link to an `i386` version of `sqlite3`. To get around this I had to `$ export ARCHFLAGS="-arch x86_64"` before running the command.

**Comment by sadlerjw** [comment]
@thislooksfun can I suggest this issue should be re-opened? I think requiring the gem to install the system `sqlite3` is not the correct solution here, especially since `extconf.rb` explicitly tries to find the brewed version: https://github.com/sparklemotion/sqlite3-ruby/blob/c8806a2fc367eb40fe87bc4818925e005be2a606/ext/sqlite3/extconf.rb#L14
Also, many other items installed by `brew` (Python 2.7.14_2, in my case) require the brewed version of sqlite3.

@PeqNP's solution worked great for me. I'd suggest the real bug to fix here is which architecture this gem tries to link against.

**Comment by fishb6nes** [comment]
This remains an issue today. 

Clean MBP13 2017 High Sierra 10.13.4
System ruby version 2.3.3p222
System sqlite3 version 3.19.3

As mentioned by sadlerjw, PeqNP's solution still works a charm.

**Comment by TimOgilvy** [comment]
Still an issue on High Sierra.

  System Version:	macOS 10.13.6 (17G65)
  Kernel Version:	Darwin 17.7.0

**Comment by GerardoOlmos** [comment]
@PeqNP solution worked on System Version: macOS 10.13.6 (17G65) with brew :). Gracias

**Comment by Diphaze** [comment]
As @PeqNP's solution did not work for me, I found a solution [here](https://stackoverflow.com/questions/41370565/ruby-sqlite3-installation-sqlite3-libversion-number-macos-sierra) and it worked :
We need to specify the built-in Mac OS X sqlite library directory as follows :
```
$ whereis sqlite3
/usr/bin/sqlite3
# if binary is in /usr/bin then library is typically in /usr/lib
$ sudo gem install sqlite3 -- --with-sqlite3-lib=/usr/lib
```

**Comment by rotemsOr** [comment]
@tenderlove THANK YOU THANK YOU!!!!
