### ISSUE TITLE
LoadError: cannot load such file -- sqlite3/sqlite3_native

### ISSUE THREAD

**Issue by RichardGregoryHamilton** [sparklemotion/sqlite3-ruby#160]
I upgraded to Ruby version 2.2.2p95 and am trying to create a database in Ruby on Rails. I get this message

    LoadError: cannot load such file -- sqlite3/sqlite3_native

I am using sqlite3 1.3.10

Any ideas?

**Comment by bizos** [comment]
me too, please help.

**Comment by larskanis** [comment]
Duplication of https://github.com/sparklemotion/sqlite3-ruby/issues/150 .

**Comment by luislavena** [comment]
Closing as dup of #150
