### ISSUE TITLE
undefined symbol: init_sqlite3_database

### ISSUE THREAD

**Issue by stolt45** [sparklemotion/sqlite3-ruby#163]
I built sqlite3 from source and built the gem with some options pointing to the libs, sqlite3.h file, and the sqlite3 binary. The gem built fine but when I require sqlite3 in irb I'm getting the following:

```ruby
$ irb
irb(main):001:0> require 'sqlite3'
irb: symbol lookup error: /app/vendor/ruby-2.0.0/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.10/lib/sqlite3/sqlite3_native.so: undefined symbol: init_sqlite3_database
```

I'm curious if it's possible to build the gem w/ a non-default install of sqlite3?

**Comment by luislavena** [comment]
Please provide more details on context, version of Ruby, version of sqlite3 was build against, compiler, version of Linux, steps used.

The more details you provide the easier will be to either reproduce or determine what is wrong.

**Comment by stolt45** [comment]
Thanks for getting back Luis. I forgot to update this saying I fixed the problem. I was using the wrong flags during the gem install. 

FWIW I used this build: https://github.com/stolt45/heroku-sqlite3 and these flags to do the install `--with-sqlite3-dir=/app/heroku-sqlite3`

I'm happy to provide any additional info if you see others running into similar things.
