### ISSUE TITLE
WITH RECURSION ... SELECT gives error

### ISSUE THREAD

**Issue by xa72** [sparklemotion/sqlite3-ruby#167]
Hi there,
I'm using 1.3.11, when I call a query with con.execute and the following content:
>			WITH RECURSIVE dates(date) AS (
>				VALUES(DATE('2014-12-01'))
>				UNION ALL
>				SELECT date(date, '+1 day')
>				FROM dates
>				WHERE date < DATE('2015-01-01')
>			)
>			SELECT
>				d.date AS datum
>			FROM dates d

I get 

> /home/nath/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize': near "WITH": syntax error (SQLite3::SQLException)
>	from /home/nath/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
>	from /home/nath/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
>	from /home/nath/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
>	from /home/nath/work/optor/ply/bin/ProblemdefinitionWriter.rb:401:in `import_from_mysql'
>	from ./problemdatei_generieren.rb:58:in `<main>'

When I execute the same query in sqlitemanager (Firefoxplugin), it works. I have no problem with other queries, so I quess, you don't yet support WITH ... SELECT. Is there a way to work around that?

Cheers Alex

**Comment by kwent** [comment]
Same here.

**Comment by xa72** [comment]
Ah, by the way, "INSERT INTO .... WITH RECURSIVE ... SELECT ...;" doesn't work either.

**Comment by kwent** [comment]
@xa72 I fixed it.

This library is a wrapper on top of sqlite3 C API. I needed to update my sqlite3 on ma machine who was a version from 2013 (`3.8.2-1`). I upgraded sqlite3 to `3.8.11.1-1` and those queries are now working.

Some commands line who can be useful:

```bash
sqlite3 --version
apt-cache show sqlite3
```

How i fix it:

```bash
echo "deb http://us.archive.ubuntu.com/ubuntu wily main" >> /etc/apt/sources.list
apt-get update
apt-get install sqlite3
```

Regards,

**Comment by xa72** [comment]
Thank you!
