### ISSUE TITLE
User-created functions that create Ruby objects can segfault -- RB_GC_GUARD unreliable

### ISSUE THREAD

**Issue by jimflood** [sparklemotion/sqlite3-ruby#171]
If a user-created function itself creates Ruby objects, you can easily produce a segfault just by driving that function hard, i.e. call it a lot of times and it will eventually crash, hard.

I suspect that it is due to garbage collection, but I'm not sure. However, putting the VALUE pointers all on the stack seems to fix this. I will submit a pull request with the fix that I propose, which is to allocate the array of params directly on the stack, rather than with xcalloc. The argc is only counting args, not rows, and if argc is a huge number then you have other problems to worry about other than eating stack space.

**Comment by tenderlove** [comment]
I think this was fixed by 380287ae5160fa460132f8cf6b65067adbeb9df4

**Comment by jimflood** [comment]
Yes. The comment in the commit tells anybody who is interested how to temporarily unfix it to see the segfault happen and compare to the fix.
