### ISSUE TITLE
Bug that causes phantom disk usage

### ISSUE THREAD

**Issue by penguinpowernz** [sparklemotion/sqlite3-ruby#173]
Say I want to get the path for my database object, how can I do that?

``` ruby
db = SQLite3::Database.new("my.db")

# I want to do this
db.path   # => /home/me/my.db
db.exist? # => true
```

Then this would be good too for checking the database exists before executing a query:

``` ruby
db = SQLite3::Database.new("my.db")

FileUtils.rm "my.db"

db.execute(".tables") # => #<SQLite3::DatabaseNotFound: SQLite3::DatabaseNotFound message: "Database not found at /home/me/my.db">
```

**Because right now, if your database is deleted, this library will hold onto the filehandle, and continue adding stuff to the deleted database**.  This will cause phantom disk usage that could fill up your disk until you reboot (or delete the handle manually from `/proc`):

``` sh
$ lsof | grep '(deleted)'
ruby      21151  server    9ur     REG        8,6    24576         21 /data/summary.db (deleted)
ruby      21151  server   10u      REG        8,6   268320         18 /data/summary.db-wal (deleted)
```

This library should be more responsible than this.

If you have the same issue and want to know how to delete it then do this (recall 21151 from the above output is the PID):

``` sh
$ cd /proc/21151/fd
$ ls -lh
lrwx------ 1 server server 64 Nov 11 16:53 63 -> /data/summary.db (deleted)
lrwx------ 1 server server 64 Nov 11 16:53 64 -> /data/summary.db-wal (deleted)
$ :> 64 # truncate the wal file
$ :> 63 # truncate the database file
$ kill 21151
```

**Comment by penguinpowernz** [comment]
I guess having this library checking the filesystem every time would make it quite a bit slower.

**Comment by penguinpowernz** [comment]
Made a pull request for this on #174 - added a new class called SafeDatabase that checks the filesystem for DB existence.

**Comment by penguinpowernz** [comment]
It should be noted that this will only happen on POSIX systems.  Others will not let an open file be deleted.

**Comment by penguinpowernz** [comment]
FYI there is some discussion going on around this over in #174.

**Comment by penguinpowernz** [comment]
FYI new pull request to handle this using bitmasks over on #180.

**Comment by flavorjones** [comment]
#180 was merged, closing this.
