### ISSUE TITLE
Travis CI build fails for Ruby 1.8.7 for any pull request

### ISSUE THREAD

**Issue by jimflood** [sparklemotion/sqlite3-ruby#175]
This line in ext/sqlite3/extconf.rb:

asplode('sqlite3') unless find_library 'sqlite3', 'sqlite3_libversion_number'

fails for only Ruby 1.8.7.

The log shows this:
/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -I. ../../../../ext/sqlite3/extconf.rb --with-opt-dir=/home/travis/build/sparklemotion/sqlite3-ruby/ports/x86_64-unknown-linux-gnu/sqlite3/3.8.11.1

`--with-opt-dir` is being passed. 

The extconf.rb has this:
`# --with-sqlite3-{dir,include,lib}`
`dir_config("sqlite3")`

I don't see the source that executes extconf.rb. Either you need an explicit --with-opt-lib (note: *lib* not *dir*) or --with-sqlite3-lib in the command line, or, something is different (a typo?) in the configuration file for 1.8.7. (I can't see where SQLite3 is being installed, looking at the log, but in the case of 1.8.7 it is going somewhere else, or something is causing mkmf's find_library to not see it.

**Comment by tenderlove** [comment]
The 1.8 build should be fixed on master now.  Try rebasing your pull requests against master and let me know if it still breaks.
