### ISSUE TITLE
LoadError on Windows x64, Ruby 2.3

### ISSUE THREAD

**Issue by belgoros** [sparklemotion/sqlite3-ruby#185]
I tried to run the newly generated Rails app on a Windows x64 PC and it failed:

```
$ rails s
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x64-mingw32/lib/sqlite3.rb:6:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x64-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x64-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from D:/Users/Serguei/Mes documents/projects/rails_draft/config/application.rb:16:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>
```

**Environment**:
- Windows 7 x64
- Ruby **2.3**
- Rails **4.2.6**

To reproduce:
- create a Rails app `rails new rails_app -T`
- run bundle
- run `rails s`

Any tips on how to solve that ?

Thank you.

**Comment by deebloomer** [comment]
+ 1 for windows 10

**Comment by ArieShout** [comment]
Is there a workaround for this, before the pull request get merged and released?

**Comment by mlt** [comment]
@ArieShout I had the same problem. Rebuilding from source as is did resolve issue for me on Windows 7 64 bit without aforementioned commit. Here are the steps:

0. Install DevKit
1. Get autoconf version of sqlite3 sources from https://www.sqlite.org/download.html
2. Start msys shell of DevKit (I have gcc from strawberry perl on PATH, this way I'm sure correct compiler is used)
3. In unpacked location for your sqlite3 configure static version only `./configure  --disable-shared`
4. Build and install it `make install DESTDIR=/c/dev/ruby/tmp`
5. Remove all existing sqlite3 gems `gem uninstall sqlite3 --all`
6. Build and install this gem `gem install sqlite3 --platform=ruby -- --with-sqlite3-include=/c/dev/ruby/tmp/usr/local/include --with-sqlite3-lib=/c/dev/ruby/tmp/usr/local/lib`

You may change path where you stage sqlite3 binaries.

Note that folder structure of final gem is different. It has no subfolders for various ruby versions.

**Comment by ArieShout** [comment]
@mlt I resolved the problem similar to your steps. This does work when you require =sqlite3= in Ruby. However, when used in Rails, the bundler will install the native version, which doesn't work. I have to run bundle update, uninstall the native version with =gem uninstall=, and then edit the =sqlite3= entry in the Gemfile.lock to =sqlite3 (1.3.11)=.

**Comment by Ajedi32** [comment]
The error is coming from [`sqlite3-ruby/lib/sqlite3.rb`](https://github.com/sparklemotion/sqlite3-ruby/blob/v1.3.11/lib/sqlite3.rb#L3-L4):

```ruby
# support multiple ruby version (fat binaries under windows)
begin
  RUBY_VERSION =~ /(\d+\.\d+)/
  require "sqlite3/#{$1}/sqlite3_native"
rescue LoadError
  require 'sqlite3/sqlite3_native'
end
```

Even in the latest release of `sqlite3-ruby`, `sqlite3/2.3/sqlite3_native` simply does not exist, which is why the error is being thrown.

**Comment by Ajedi32** [comment]
It seems #186 should fix this for future releases.

In the meantime I'm just going to downgrade to Ruby 2.2. Getting the build to work on Windows is a pain, and I don't want new developers on my project to have to go through process just to be able to run the tests.

**Comment by larskanis** [comment]
Yes PR #186 fixes this issue.

**Comment by vietstrong** [comment]
Hello all,
The solution is:
Edit file sqlite3-x.x.x.gemspec, change  s.require_paths=["lib"] to s.require_paths=["lib/sqlite3_native"]

Linux/UNIX: /usr/local/share/gem/specifications/

Windows: C:\Ruby...\lib\ruby\gems\x.x.x\specifications\

**Comment by rubycoder** [comment]
@vietstrong I tried your fix, but unfortunately it didn't work for me on Win 7 Pro SP1 64 bit (running 32 bit version of Ruby)

	C:\Users\wayne\blog>ruby -v
	ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
	C:\Users\wayne\blog>irb
	irb(main):001:0> require 'sqlite3'
	LoadError: cannot load such file -- sqlite3/sqlite3_native
			from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from c:/Ruby/Ruby231p112/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x86-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
			from c:/Ruby/Ruby231p112/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x86-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
			from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
			from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
			from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
			from (irb):1
			from c:/Ruby/Ruby231p112/bin/irb.cmd:19:in `<main>'

Here I edited C:\Ruby\Ruby231p112\lib\ruby\gems\2.3.0\specifications\sqlite3-1.3.11-x86-mingw32.gemspec
to change
      s.require_paths = ["lib".freeze]
to
      s.require_paths = ["lib/sqlite3_native".freeze]

	C:\Users\wayne\blog>irb
	irb(main):001:0> require 'sqlite3'
	LoadError: cannot load such file -- sqlite3
			from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
			from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
			from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
			from (irb):1
			from c:/Ruby/Ruby231p112/bin/irb.cmd:19:in `<main>'

**Comment by vietstrong** [comment]
Dear man,
With Win 7 Pro SP1 64 bit please install:
C:\Users\TRONG>ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x64-mingw32]

C:\Users\TRONG>sqlite3 -version
3.14.2 2016-09-12 18:50:49 29dbef4b8585f753861a36d6dd102ca634197bd6

C:\Users\TRONG>rails -v
Rails 5.0.0.1

C:\Users\TRONG>

Regards,
Trong

**Comment by rubycoder** [comment]
@vietstrong Hi Trong, yes, I've tried using the versions you suggested and that does work.  Thanks for your comment.

Best regards,
Wayne

**Comment by hwding** [comment]
Guys, try the instructions [here](https://github.com/hwding/sqlite3-ruby-win), no need to downgrade your sqlite3 gem or ruby.

**Comment by thisismydesign** [comment]
If you're interested in workarounds try all answers here: https://stackoverflow.com/questions/17643897/cannot-load-such-file-sqlite3-sqlite3-native-loaderror-on-ruby-on-rails

**Comment by larskanis** [comment]
I added another solution for using sqlite3 on RubyInstaller-2.4, 2.5 or [2.6](https://rubyinstaller.org/2017/12/24/rubyinstaller-head-available.html) to this [stackoverflow question](https://stackoverflow.com/questions/17643897/cannot-load-such-file-sqlite3-sqlite3-native-loaderror-on-ruby-on-rails).

**Comment by mallikarjunece** [comment]
> @vietstrong I tried your fix, but unfortunately it didn't work for me on Win 7 Pro SP1 64 bit (running 32 bit version of Ruby)
> 
> ```
> C:\Users\wayne\blog>ruby -v
> ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
> C:\Users\wayne\blog>irb
> irb(main):001:0> require 'sqlite3'
> LoadError: cannot load such file -- sqlite3/sqlite3_native
>         from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>         from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>         from c:/Ruby/Ruby231p112/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x86-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
>         from c:/Ruby/Ruby231p112/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x86-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
>         from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
>         from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
>         from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
>         from (irb):1
>         from c:/Ruby/Ruby231p112/bin/irb.cmd:19:in `<main>'
> ```
> Here I edited C:\Ruby\Ruby231p112\lib\ruby\gems\2.3.0\specifications\sqlite3-1.3.11-x86-mingw32.gemspec
> to change
> s.require_paths = ["lib".freeze]
> to
> s.require_paths = ["lib/sqlite3_native".freeze]
> 
> ```
> C:\Users\wayne\blog>irb
> irb(main):001:0> require 'sqlite3'
> LoadError: cannot load such file -- sqlite3
>         from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
>         from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
>         from c:/Ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
>         from (irb):1
>         from c:/Ruby/Ruby231p112/bin/irb.cmd:19:in `<main>'
> ```

+1

**Comment by flavorjones** [comment]
We're working on shipping precompiled native gems as well as increasing test coverage for people who want to use system libraries. If you're curious please follow #320.
