### ISSUE TITLE
Incorporate some of sqlite_ext gem capabilities and/or enable cleaner extension?

### ISSUE THREAD

**Issue by stevecj** [sparklemotion/sqlite3-ruby#189]
I wrote https://rubygems.org/gems/sqlite_ext to provide a means of registering function definitions to make sure they will be created on all new instances of `SQLite3::Database`. It also provides a means of asking a `SQLite3::Database` instance what functions have been created on it.

I'm thinking that it would certainly make sense to add the functionality to ask the db instance about its created functions into the sqlite3 gem.

I'm not sure that the registering of functions to be created on each new instance should be added to the sqlite3 gem, but maybe add a better way to hook into it? I'm currently `prepend`ing a module to override `initialize` and call the original `initialize` via `super`, but it would be nice to have an explicit API for hooking in that kind of thing.

**Comment by tenderlove** [comment]
I am open to suggestions, but at first glance reading this I would recommend that you provide a subclass of `SQLite3::Database` and ask that users instantiate your class. That way you have full control over what functions are registered, etc.  Please feel free to open a PR if you have some suggestions for extension.

Thanks!
