### ISSUE TITLE
SIGABRT on OSX 10.12 (Sierra) after fork() 

### ISSUE THREAD

**Issue by onyxraven** [sparklemotion/sqlite3-ruby#195]
Crash Log and DiagnosticReport: https://gist.github.com/onyxraven/ce190bc4c9f31db07ec3c27578d33641

When running rspec via spring, ruby almost immediately crashes with the attached crash info.  This is within my rails app, but I can try to get a simpler example put together later today.

What it looks like is the libsqlite3.dylib bundled with Sierra may not be safe for use across a fork.  

There is a similar report on the python list https://bugs.python.org/issue27126, and someone else added a bug to the ruby bug list https://bugs.ruby-lang.org/issues/12781.

I've attempted to get the gem to use a different version (eg, the one in Homebrew), but so far I've failed to get it to load anything but the version out of /usr/lib/ - If I can get that workaround figured out, it would get me past this issue for the short term.

If ruby is not forking (eg, via SPRING_DISABLE, or other non-forking code), the sqlite3 code still works fine.

**Comment by kumasento** [comment]
I'm facing the same issue.

**Comment by Yanchek99** [comment]
Same here causing seg faults.

**Comment by rhutch117** [comment]
Same issue.

**Comment by markwpiper** [comment]
+1

**Comment by rhutch117** [comment]
same issue

**Comment by markwpiper** [comment]
Was able to workaround it by installing the sqlite3 gem and forcing it to use the newer version of sqlite from my homebrew installation:

gem uninstall sqlite3
gem install sqlite3 -- --with-sqlite3-include=/usr/local/Cellar/sqlite/3.14.2_1/include --with-sqlite3-lib=/usr/local/Cellar/sqlite/3.14.2_1/lib

**Comment by rhutch117** [comment]
I tried that workaround and now rails crashes whenever I try to run a rails console in terminal. Is there an easy way to roll that back?

**Comment by electrickite** [comment]
Also experiencing this issue on macOS Sierra, specifically with v1.3.11. Seems to occur when running a Rails console under spring or using rake to start Resque workers.

In some cases, I can avoid the segfault by setting the environment variable `DISABLE_SPRING=1`

**Comment by jdongelmans** [comment]
Also having this issue.
Thanks @markwpiper for the workaround!

**Comment by ccasabona** [comment]
Thanks to markwpiper for a working fix!

**Comment by tenderlove** [comment]
Thanks for reporting this.  Seems like we're in the same boat as the Python folks.  I'd prefer not to embed SQLite3 but maybe we can ship a version that looks for SQLite3 in homebrew before trying to use the system library.  Does this seem reasonable to everyone?

In the mean time, you can shorten @markwpiper's workaround to:

```
gem install sqlite3 -- --with-sqlite3-dir=/usr/local/Cellar/sqlite/3.14.2_1
```

**Comment by excid3** [comment]
Seems like a reasonable solution to me.

**Comment by tenderlove** [comment]
I just pushed `1.3.12`.  It contains c7226bac53f3c43df0f0374ef89de072327ef261, which should fix this problem.  You can verify the installed version is linked against homebrew's installed version of SQLite3 by doing `otool -L $(gem which sqlite3/sqlite3_native.bundle)`.  The output should look something like this:

```
[aaron@TC pkg (master)]$ otool -L $(gem which sqlite3/sqlite3_native.bundle)
/Users/aaron/.rbenv/versions/ruby-trunk/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.12/lib/sqlite3/sqlite3_native.bundle:
	/usr/local/opt/sqlite/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/local/opt/gperftools/lib/libprofiler.0.dylib (compatibility version 5.0.0, current version 5.8.0)
[aaron@TC pkg (master)]$
```

The important line is where it says `/usr/local/opt/sqlite/lib/libsqlite3.0.dylib`, which is from homebrew.

I close this if someone can verify the new version fixes the issue.  Thank you!

**Comment by excid3** [comment]
@tenderlove Just tested it, can confirm 1.3.12 works great! 🤘 

```
○ otool -L $(gem which sqlite3/sqlite3_native.bundle)
/Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.12/lib/sqlite3/sqlite3_native.bundle:
	/usr/local/opt/sqlite/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.1.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by tenderlove** [comment]
@excid3 great! Thank you for testing.  I'll close this ticket now. 😄

**Comment by ccasabona** [comment]
I upgraded the version and the fix is working perfectly.  Thank you.

Charlie

**Comment by spikex** [comment]
Worked for me as well. Thanks!

**Comment by synth** [comment]
This did not work for me running spork with ruby v1.9.3-p547. I uninstalled the gem, uninstalled the brew, and reinstalled both following the above directions.

**Comment by jakeonrails** [comment]
I'm still having this issue.

I've tried:

```
gem install sqlite3 -- --with-sqlite3-dir=/usr/local/Cellar/sqlite/3.14.2_1
```

I've reinstalled Ruby 2.2.5 via `rvm reinstall 2.2.5`

I've manually uninstalled sqlite3 and reinstalled

I've uninstalled sqlite from brew and reinstalled

I've tried `brew link --force sqlite`

I'm running sqlite3 1.3.12.

My otool output:

```
otool -L $(gem which sqlite3/sqlite3_native.bundle)
/Users/jakemoffatt/.rvm/gems/ruby-2.2.5/gems/sqlite3-1.3.12/lib/sqlite3/sqlite3_native.bundle:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/local/opt/sqlite/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

Is the problem that the `/usr/lib/libz` version is shown first? How do I fix that?

My specific error message, migrating a brand new Rails 5 app:

```
$ rake db:migrate
Running via Spring preloader in process 69525
/Users/jakemoffatt/.rvm/gems/ruby-2.2.5/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:27: [BUG] Segmentation fault at 0x00000000000110
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin16]
```

**Comment by ascarter** [comment]
I think I'm hitting it as well even using Homebrew sqlite3:

```
$ otool -L $(gem which sqlite3/sqlite3_native.bundle)
/Users/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.12/lib/sqlite3/sqlite3_native.bundle:
	/opt/homebrew/opt/sqlite/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

Running tests suites on the depot iteration b1 (pragprog Agile Web Development with Rails 5):

```
bin/rails test
Running via Spring preloader in process 11300
/Users/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:27: [BUG] Segmentation fault at 0x00000000000110
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
```

Installed sqlite3 from homebrew:

```
$ brew info sqlite
sqlite: stable 3.15.2 (bottled) [keg-only]
Command-line interface for SQLite
https://sqlite.org/
/opt/homebrew/Cellar/sqlite/3.15.2 (11 files, 2.9M)
  Poured from bottle on 2016-12-02 at 20:50:18
```

Tried:

```
gem install sqlite3
gem install sqlite3 -- --with-sqlite3-dir=/opt/homebrew/Cellar/sqlite/3.15.2
```

**Comment by pinewong** [comment]
Me too.
macOS 10.12.1
Rails 5.0.0.1

**Comment by ccasabona** [comment]
Some food for thought for this problem:

The problem started after upgrading to OS Sierra.  Changes to the source code in development caused a segmentation fault error.  Restarting the development server (puma) fixed this.  At the time, I was using Rails 5.0.0 and ruby 2.3.1 (or maybe 2.3.0). An issue was put on github rails.  The rails team determined that this was not a rails issue, but that it was likely a problem with the sqite gem.

My understanding of the problem was that the sqlite gem not using the brew installed sqlite even when brew reported it as linked properly.  At the time, a fix was suggested (I think by the gem author) for these steps:

gem uninstall sqlite3

match the version number installed by brew install sqlite3

gem install sqlite3 -- --with-sqlite3-include=/usr/local/Cellar/sqlite/3.14.2_1/include --with-sqlite3-lib=/usr/local/Cellar/sqlite/3.14.2_1/lib

This was under version 1.3.11 of the sqlite gem.

A fix for this was incorporated into a new version of the gem and bumped the version from 1.3.11 to 1.3.12.  You could just use the gem without the complicated install command.

After installing ruby 2.3.2, the problem came back but only in the test environment when entering or removing a byebug command.  I went back to ruby 2.3.1 and the problem went away.  When ruby 2.3.3 was installed, the problem did not recur.

Currently, I am using:

OS Sierra 10.12.1
Ruby 2.3.3
Rails 5.0.0.1

running these commands

~/ brew link sqlite --dry-run
Warning: Already linked: /usr/local/Cellar/sqlite/3.15.1

~/ which sqlite3
/usr/local/bin/sqlite3

I hope this helps someone.

**Comment by arthurnn** [comment]
I think `brew info` wasn't working for me, which https://github.com/sparklemotion/sqlite3-ruby/commit/427b15ee37336ccf86ad56bafa48c4c6923175f8 fixed the issue. However that is not released yet. Can you release another release @tenderlove ?
this is my output after a install of 1.3.12:
```
[arthurnn@snowball activerecord]$ otool -L $(gem which sqlite3/sqlite3_native.bundle)
/Users/arthurnn/.gem/ruby/2.4.0/gems/sqlite3-1.3.12/lib/sqlite3/sqlite3_native.bundle:
/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 253.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.0.0)
/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)

[arthurnn@snowball activerecord]$ brew --prefix sqlite3
/usr/local/opt/sqlite
```

For now, I am using this as a solution:
```
 gem install sqlite3 -- --with-sqlite3-dir=$(brew --prefix sqlite3)
```

**Comment by tenderlove** [comment]
@arthurnn 1.3.13 should be shipped now!
