### ISSUE TITLE
Use #sqlite3_exec for executing multiple statements

### ISSUE THREAD

**Issue by gazayas** [sparklemotion/sqlite3-ruby#206]
`database.rb` line 268 talks about using sqlite3's api for batch execution.
I looked at the API and thought `sqlite3_exec` would be a good function to use for this.

Thoughts?

**Comment by tenderlove** [comment]
We don't wrap the function today.  I'm not opposed to adding the function per-se, but I'm not sure what the win is over the current API in Ruby.  The use case is that you have a bunch of SQL statements that are semicolon separated?

**Comment by gazayas** [comment]
I see, yeah, they would just be separated by semi-colons.
Like I mentioned in the PR, the only plus is that it returns values, but yeah, no type casting... 🐧

**Comment by gazayas** [comment]
Pull Request #207 was merged so I'll close this issue
