### ISSUE TITLE
Jason support ?

### ISSUE THREAD

**Issue by unplugandplay** [sparklemotion/sqlite3-ruby#209]
Hi, do you plan to release support ouf thé json1 sqlite extension ?

**Comment by unixneo** [comment]
What is Jason?

<img width="444" alt="Screenshot 2023-10-27 at 8 45 49 AM" src="https://github.com/sparklemotion/sqlite3-ruby/assets/12891828/3e0eec99-6c59-4956-9a25-d21c6e793cff">

**Comment by flavorjones** [comment]
There's no json1 extension anymore. From https://www.sqlite.org/json1.html

> The JSON functions and operators are built into SQLite by default, as of SQLite version 3.38.0 (2022-02-22). They can be omitted by adding the -DSQLITE_OMIT_JSON compile-time option. Prior to version 3.38.0, the JSON functions were an extension that would only be included in builds if the -DSQLITE_ENABLE_JSON1 compile-time option was included. In other words, the JSON functions went from being opt-in with SQLite version 3.37.2 and earlier to opt-out with SQLite version 3.38.0 and later.

But I understand that you're probably also asking, "will there be first-class support for the json functions". Although I have no plans to implement that functionality, I would welcome contributions, and would gladly assist, if someone wanted to design that API and implement it.
