### ISSUE TITLE
cannot load such file -- sqlite3 (LoadError)

### ISSUE THREAD

**Issue by MarkVortman** [sparklemotion/sqlite3-ruby#224]
Can you help? I'm new to development on Ruby. I tried to use SQLite in my app ( `require 'sqlite3'` ) and : 
```
main.rb:5:in `require': cannot load such file -- sqlite3 (LoadError)
        from main.rb:5:in `<main>'
```

`Windows 10 x64`
`ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]`
`SQLite version 3.22.0 2018-01-22 18:45:57`
```
*** LOCAL GEMS ***

actioncable (5.1.4)
actionmailer (5.1.4)
actionpack (5.1.4)
actionview (5.1.4)
activejob (5.1.4)
activemodel (5.1.4)
activerecord (5.1.4)
activesupport (5.1.4)
arel (8.0.0)
axiom-types (0.1.1)
bigdecimal (default: 1.3.0)
builder (3.2.3)
bundler (1.16.1)
coercible (1.0.0)
concurrent-ruby (1.0.5)
crass (1.0.3)
descendants_tracker (0.0.4)
did_you_mean (1.1.0)
equalizer (0.0.11)
erubi (1.7.0)
faraday (0.14.0)
globalid (0.4.1)
i18n (0.9.3)
ice_nine (0.11.2)
inflecto (0.0.2)
io-console (default: 0.4.6)
json (default: 2.0.4)
loofah (2.1.1)
mail (2.7.0)
method_source (0.9.0)
mini_mime (1.0.0)
mini_portile2 (2.3.0)
minitest (5.10.1)
multipart-post (2.0.0)
net-telnet (0.1.1)
nio4r (2.2.0)
nokogiri (1.8.1 ruby x64-mingw32)
openssl (default: 2.0.5)
power_assert (0.4.1)
psych (default: 2.2.2)
rack (2.0.3)
rack-test (0.8.2)
rails (5.1.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
railties (5.1.4)
rake (12.0.0)
rdoc (default: 5.0.0)
sprockets (3.7.1)
sprockets-rails (3.2.1)
sqlite3 (1.3.13)
telegram-bot-ruby (0.8.6.1)
test-unit (3.2.3)
thor (0.20.0)
thread_safe (0.3.6)
tzinfo (1.2.4)
virtus (1.0.5)
websocket-driver (0.6.5)
websocket-extensions (0.1.3)
xmlrpc (0.2.1)
```

**Comment by thisismydesign** [comment]
If you're on Windows try all answers here (or don't be on Windows because Ruby support sucks): https://stackoverflow.com/questions/17643897/cannot-load-such-file-sqlite3-sqlite3-native-loaderror-on-ruby-on-rails

**Comment by WilfredoAlarcon** [comment]
I tried go to Gem file in your proyect and put following code:
gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"

now in your terminal: 



I using rails 5.2.1 and

**Comment by thisismydesign** [comment]
@WilfredoAlarcon The issue might be operating system dependent.

**Comment by WilfredoAlarcon** [comment]
@thisismydesign It works for me based in Windows 10 OS.

**Comment by manuelvargastapia** [comment]
@WilfredoAlarcon Thanks man! It works for me. This is an issue with Rails 5.2, I guess

**Comment by humbertofialho** [comment]
> I've tried go to Gem file in your proyect and put following code:
> gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
> 
> now in your terminal:
> bundle install
> 
> I'm using rails 5.2.1 and ruby version 2.5.1
> 
> It should work for you if you using ruby v. 2.4.3!.

Nice answer! I did it and solve my problem! Thanks so much

**Comment by sounishnath003** [comment]
> I've tried go to Gem file in your proyect and put following code:
> gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
> 
> now in your terminal:
> bundle install
> 
> I'm using rails 5.2.1 and ruby version 2.5.1
> 
> It should work for you if you using ruby v. 2.4.3!.

" You are Awesome " ... ;-)

**Comment by jenstreetman** [comment]
Thank you! This worked for me too!

**Comment by Hatnice** [comment]
Issue persists,

Errno::ENOENT: No such file or directory - git clone "https://github.com/larskanis/sqlite3-ruby"

**Comment by o1esh** [comment]
вы все дауны

**Comment by o1esh** [comment]
суки ненавижу вас

**Comment by shuxinjin** [comment]
This worked for me too!

**Comment by allanwei** [comment]
I've tried go to Gem file in your proyect and put following code:
gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"

now in your terminal:
bundle install

I'm using rails 5.2.1 and ruby version 2.5.1

It should work for you if you using ruby v. 2.4.3!.

it work for me.

**Comment by Genjudoki** [comment]
@WilfredoAlarcon, i confirme this solution. I'm working with Ruby 2.5.3/ rails 5.2 on Windows 10. Thanks you!
gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
bundle install

**Comment by rahulsinghidrive** [comment]
I get this following error when I try the above solution:
`First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clone+%22https+%2F%2Fgithub.com%2Flarskanis%2Fsqlite3-ruby%22+%22C+%2FRuby25-x64%2Flib%2Fruby%2Fgems%2F2.5.0%2Fcache%2Fbundler%2Fgit%2Fsqlite3-ruby-4bbfb5149b3916ce8777e4e6b7505bba5e72d1e3%22+--bare+--no-hardlinks+--quiet&type=Issues`

ruby version: 2.5.3
rails version: 5.2.1.1
@WilfredoAlarcon please check.

**Comment by fanfan1609** [comment]
@WilfredoAlarcon 
Thanks for your awesome answer. I had stuck yesterday.

**Comment by srfinkel** [comment]
Thanks @WilfredoAlarcon !!

**Comment by sounishnath003** [comment]
Lovely.. glad to here you 😍.
By the way, do you know how to make a chatbot using ruby ?
I WANT to know how to build this..

**Comment by MimoMoreno** [comment]
@WilfredoAlarcon 
I am working with rails 5.0.6 and ruby 2.3.3 and this is the result of running `bundle install` after changing the Gemfile:
``
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/bundler/gems/sqlite3-ruby-102750907917/ext/sqlite3
C:/RailsInstaller/Ruby2.3.3/bin/ruby.exe -r ./siteconf20190106-33920-1ph85e1.rb
extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
.....
.....
Gem files will remain installed in
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/bundler/gems/sqlite3-ruby-102750907917
for inspection.
Results logged to
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/bundler/gems/extensions/x86-mingw32/2.3.0/sqlite3-ruby-102750907917/gem_make.out

An error occurred while installing sqlite3 (1.3.13.20180326210955), and Bundler
cannot continue.

In Gemfile:
  sqlite3
``

I'd appreciate some help!

**Comment by alon1samuel** [comment]
This worked for me:
[https://github.com/sparklemotion/sqlite3-ruby/issues/240#issuecomment-432501696](url)

**Comment by WilfredoAlarcon** [comment]
I'm sorry about what went on 'til I had been working on an important project. I'll check it , then Ima give my feedback about that issue.

Regards,

Wilfredo.

**Comment by ehmatt** [comment]
> @WilfredoAlarcon
> I am working with rails 5.0.6 and ruby 2.3.3 and this is the result of running `bundle install` after changing the Gemfile:
> 
> ```
> Fetching https://github.com/larskanis/sqlite3-ruby
> Fetching gem metadata from https://rubygems.org/.............
> Fetching version metadata from https://rubygems.org/...
> Fetching dependency metadata from https://rubygems.org/..
> Resolving dependencies........
> ......
> ......
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> 
> current directory:
> C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/bundler/gems/sqlite3-ruby-102750907917/ext/sqlite3
> C:/RailsInstaller/Ruby2.3.3/bin/ruby.exe -r ./siteconf20190106-33920-1ph85e1.rb
> extconf.rb
> checking for sqlite3.h... no
> sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> .....
> .....
> Gem files will remain installed in
> C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/bundler/gems/sqlite3-ruby-102750907917
> for inspection.
> Results logged to
> C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/bundler/gems/extensions/x86-mingw32/2.3.0/sqlite3-ruby-102750907917/gem_make.out
> 
> An error occurred while installing sqlite3 (1.3.13.20180326210955), and Bundler
> cannot continue.
> 
> In Gemfile:
>   sqlite3
> ```
> I'd appreciate some help!

I also got this error, anybody have suggestions for fixing it?

**Comment by sloppycoder** [comment]
gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"

worked for me. 
windows 10
ruby 2.5.3-1
rails 5.2.2

but without this line in Gemfile, bundler tried to use 1.4.0 version of sqlite3 gem, still fails.

**Comment by total-anachronism** [comment]
did everything listed above, and after bundle install I'm getting  'could not locate Gemfile'

I'm on windows 10
ruby 2.5.3p105 
rails 5.2.3

Any insight would be most appreciated.

**Comment by pineappledreams** [comment]
> 
> 
> did everything listed above, and after bundle install I'm getting 'could not locate Gemfile'
> 
> I'm on windows 10
> ruby 2.5.3p105
> rails 5.2.3
> 
> Any insight would be most appreciated.

@total-anachronism , I got some good news for you, bud. I am running the same specs as you, windows 10 and everything.

I looked into this Japanese blogpost: https://qiita.com/shita_fontaine/items/aa3f762d7afa20c5d42a and man, I finally got it to work. Here's how.

First when creating a new rails project, make sure to add --skip-bundle into the end. So, for example, if you are following getting started section on railsguides and wanna create a blog the command on your shell command should be:
```
$ rails new blog --skip-bundle
````
This will allow you to get a jump on the damn thing. If you let the bundler run in the end and then try to change the gemfile, bundler will stubbornly install 1.4.0 version of sqlite3, which will fail to compile every single time.

So once it generates the base for you and you have successfully skipped the bundler in the end, NOW 
change the line in the GemFile:
```
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
```
to (as @WilfredoAlarcon has shown)
```
# Use sqlite3 as the database for Active Record
gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
```
then run on your shell
```
$ bundle install
```
You will see that bundler will say bundle complete!, install the desired 1.3.13 version of sqlite3 from the git repo and when you run rails server, and breathe in relief that you will be able to access the damn server you worked so hard to get on to.

Let me know how it goes.

**Comment by total-anachronism** [comment]
Hey @pineappledreams--

Thanks for the assist-- I'll let you know if I get it to work. I'm pretty new to learning code, and I feel like I got thrown directly into the deep, dark, shrieking eel-infested end of the pool trying to install RoR. Ironically, during the multiple attempts, I never had a problem with the actual Ruby, Rails, or gems installs (except for the time above)-- its sqlite3/mysql/postgresql and other peripheral programs that have been driving me around the bend (plus I couldn't get Atom or Sublime Text to hook in-that's a side effect of the sql problem, right? And I also ran into a problem with a key that GitHub wanted-- I got one to generate, but it was in the wrong format... so yeah, its been quite a thing). I downloaded and installed Ubuntu to give the Linux platform a try, and kept running into walls there as well. I have learned quite a bit trying to unknot everything, so at least there's that, right?

Thanks again for the links and I'll update if I can finally get on Rails!

**Comment by Thornybastard** [comment]
> 
> 
> > did everything listed above, and after bundle install I'm getting 'could not locate Gemfile'
> > I'm on windows 10
> > ruby 2.5.3p105
> > rails 5.2.3
> > Any insight would be most appreciated.
> 
> @total-anachronism , I got some good news for you, bud. I am running the same specs as you, windows 10 and everything.
> 
> I looked into this Japanese blogpost: https://qiita.com/shita_fontaine/items/aa3f762d7afa20c5d42a and man, I finally got it to work. Here's how.
> 
> First when creating a new rails project, make sure to add --skip-bundle into the end. So, for example, if you are following getting started section on railsguides and wanna create a blog the command on your shell command should be:
> 
> ```
> $ rails new blog --skip-bundle
> ```
> 
> This will allow you to get a jump on the damn thing. If you let the bundler run in the end and then try to change the gemfile, bundler will stubbornly install 1.4.0 version of sqlite3, which will fail to compile every single time.
> 
> So once it generates the base for you and you have successfully skipped the bundler in the end, NOW
> change the line in the GemFile:
> 
> ```
> # Use sqlite3 as the database for Active Record
> gem 'sqlite3'
> ```
> 
> to (as @WilfredoAlarcon has shown)
> 
> ```
> # Use sqlite3 as the database for Active Record
> gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
> ```
> 
> then run on your shell
> 
> ```
> $ bundle install
> ```
> 
> You will see that bundler will say bundle complete!, install the desired 1.3.13 version of sqlite3 from the git repo and when you run rails server, and breathe in relief that you will be able to access the damn server you worked so hard to get on to.
> 
> Let me know how it goes - because I did some wicked dragging and dropping of sqlite files and setting paths and whatever and it just kinda worked at one point from now on. If it works for you too - then great!

This worked for me, but you have to have Git for Windows installed and use Git to enter the code. It won't work from Windows Command.

Also, before attempting this, I deleted the previous "blog" directory and started fresh. 

Once you have your new blog folder, Windows won't know how to open the gem file so you have to double click it  select a program, or right click and choose "open with." I used Atom. Total noobs like me probably won't know this. I just thought "Ah, shit, well, lemme try Atom, that's made _for_ coders so maybe it'll work on this..."

**Comment by conorevans98** [comment]
@Thornybastard thanks for the heads up on the Git for Windows. However, I ran into an issue there too. 

So I had the same problem first day with bundle install at sqlite3 1.4.0, fatal error missing sqlite3.h.  I was directed to this thread and tried the solutions.

 I created a new proj with --skip-bundle and then went into Gemfile and edited it to the appropriate 'gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"'. I then ran bundle install in cmd and, like you said, it didn't work (fatal: unable to access 'https://github.com/larskanis/sqlite3-ruby/').

 I then noticed your comment and downloaded Git for Windows, ran 'Git Bash here' on my project :
$ bundle install 

It succeeded in fetching from the git repository, but then threw me another error:

"Using sqlite3 1.3.13.20180326210955 from https://github.com/larskanis/sqlite3-ruby (at add-gemspec@1027509)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension."

"sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***"

So the multiple step process which threw different errors at each stage has led back to the original error at what should have been the final step. 

Any input is appreciated. I am losing my sanity.

**Comment by Thornybastard** [comment]
Did you delete the blog folder in Windows and then start over?

It's usuall in C/users/yourusername. So in my case it was in 
C/uers/admin. Just delete the whole damn folder and then create your 
new blog with --skip-bundle and try again.

**Comment by conorevans98** [comment]
Yes I have deleted and re-created my rails project. The error persisted.

**Comment by Thornybastard** [comment]
Well, I'm sorry Conorevans98, you've reached the limits of my 
knowledge.

I'll tell ya another mistake I made and you can check for it--when I 
opened the gem file in Atom and pasted in the new code, I inadvertantly 
kept the first gem on line 9 so then I had two gems together (9. gem 
gem code here) and I had to go back and edit that line. So you can 
check that your copy and paste is correct.

You're using Git bash right? Not Windows cmd?

I'm probably more noob at coding and programming than you so, not sure 
what else to tell you.....

Are you using a VPN? Sometimes that screws up fetching repos, but you 
said that wasn't the problem, it was local.

What Ruby package did you install?

Going out for the day now, hope you get help with your issue.

**Comment by conorevans98** [comment]
No double gem over here. Yes using Git bash. No not using a VPN. Rails 5.1.7, Ruby 2.3.3. Cheers for the attempt, anyway.

**Comment by Thornybastard** [comment]
I'm using Ruby 2.5.3 and Rails 5.2.3, so that could be the diff.

**Comment by Thornybastard** [comment]
Hey, I found this today while poking around. Not sure if it'll help you 
or not: 
https://stackoverflow.com/questions/36230560/how-to-install-sqlite3-on-my-windows-10-computer

**Comment by dwayneyan** [comment]
ootsnap.o: In function `atomic_write_cache_file':
C:\RailsInstaller\Ruby2.3.3\lib\ruby\gems\2.3.0\gems\bootsnap-1.4.4\ext\bootsnap/bootsnap.c:484:
undefined reference to `mkstemp'
collect2.exe: error: ld returned 1 exit status
make: *** [bootsnap.so] Error 1

make failed, exit code 2

Gem files will remain installed in
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bootsnap-1.4.4 for
inspection.
Results logged to
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/bootsnap-1.4.4/gem_make.out

An error occurred while installing bootsnap (1.4.4), and Bundler cannot
continue.
Make sure that `gem install bootsnap -v '1.4.4' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  bootsnap

I need someone to help me in ordder to fix that error.please

**Comment by conorevans** [comment]
https://www.reddit.com/r/learnprogramming/comments/b3wzv2/ruby_on_rails_sqlite3h_is_missing/ej2sn3t/ this fixed my issue with sqlite3.h not being found 👌

**Comment by Mahi6541** [comment]
C:/Ruby26/lib/ruby/gems/2.6.0/extensions/x86-mingw32/2.6.0/sqlite3-1.4.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/Ruby26/lib/ruby/gems/2.6.0/gems/sqlite3-1.4.2 for inspection.
Results logged to
C:/Ruby26/lib/ruby/gems/2.6.0/extensions/x86-mingw32/2.6.0/sqlite3-1.4.2/gem_make.out

An error occurred while installing sqlite3 (1.4.2), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  sqlite3
         run  bundle binstubs bundler
Could not find gem 'sqlite3 (~> 1.4) x86-mingw32' in any of the gem sources
listed in your Gemfile.
       rails  webpacker:install
Could not find gem 'sqlite3 (~> 1.4) x86-mingw32' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.

**Comment by MMGGYY66** [comment]
Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clone+%22https+%2F%2Fgithub.com%2Flarskanis%2Fsqlite3-ruby%22+%22C+%2FRuby26-x64%2Flib%2Fruby%2Fgems%2F2.6.0%2Fcache%2Fbundler%2Fgit%2Fsqlite3-ruby-4bbfb5149b3916ce8777e4e6b7505bba5e72d1e3%22+--bare+--no-hardlinks+--quiet&type=Issues

**Comment by NajeebAhsan** [comment]
> I've tried go to Gem file in your proyect and put following code: gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
> 
> now in your terminal: bundle install
> 
> I'm using rails 5.2.1 and ruby version 2.5.1
> 
> It should work for you if you using ruby v. 2.4.3!.
**An error occurred while installing puma (5.6.2), and Bundler cannot continue.**
it shows this error
