### ISSUE TITLE
can not upsert

### ISSUE THREAD

**Issue by soukouki** [sparklemotion/sqlite3-ruby#238]
https://sqlite.org/lang_UPSERT.html

```sql
CREATE TABLE vocabulary(word TEXT PRIMARY KEY, count INT DEFAULT 1);
INSERT INTO vocabulary(word) VALUES('jovial')
  ON CONFLICT(word) DO UPDATE SET count=count+1;
```
```
lib/sqlite3/database.rb:91:in `initialize': near "ON": syntax error (SQLite3::SQLException)
```

**Comment by luikore** [comment]
I met with the same bug in Linux with versions:

```
SQLite3::VERSION # 1.4.1
SQLite3::SQLITE_VERSION # 3.28.0
```

The same upsert statement works in:

- macOS gem
- Linux sqlite commandline

But raises syntax error in gem in Linux.

**Comment by flavorjones** [comment]
The "ON CONFLICT" upsert feature was added to upstream sqlite3 in v3.24.0. I can't reproduce what you're describing with a version later than that, specifically trying with v1.5.0.rc1 which uses libsqlite3 v3.39.0.
