### ISSUE TITLE
I've tried go to Gem file in your proyect and put following code:

### ISSUE THREAD

**Issue by Amir998** [sparklemotion/sqlite3-ruby#244]
I've tried go to Gem file in your proyect and put following code:
gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"

now in your terminal: 
bundle install

I'm using rails 5.2.1 and ruby version 2.5.1

It should work for you if you using ruby v. 2.4.3!.

_Originally posted by @WilfredoAlarcon in https://github.com/sparklemotion/sqlite3-ruby/issues/224#issuecomment-416800097_

Hey, I tried to do this and this error popped:

The git source https://github.com/larskanis/sqlite3-ruby is not yet checked out. Please run `bundle install` before trying to start your application

And when I run bundle install, another error appears. What do I do?

**Comment by stomar** [comment]
What‘s the other error? And the OS?

**Comment by dalfaro7** [comment]
unable to access 'https://github.com/larskanis/sqlite3-ruby/': error:1407742E:SSL
