### ISSUE TITLE
The new 1.4 version brokes "rails new" experience for all existent Rails versions.

### ISSUE THREAD

**Issue by sponomarev** [sparklemotion/sqlite3-ruby#247]
https://github.com/rails/rails/issues/35161 for cross-reference

**Comment by tenderlove** [comment]
This doesn't seem like a bug in SQLite. Rails should be less brittle.

**Comment by sponomarev** [comment]
Closing since it's not considered a SQLite bug

**Comment by a-liudezhi** [comment]
新版本1.4.1 有问题
