### ISSUE TITLE
Gem::LoadError:   Specified 'sqlite3' for database adapter, but the gem is not loaded.

### ISSUE THREAD

**Issue by brendon** [sparklemotion/sqlite3-ruby#249]
Hi there, I ran into a weird issue that you can see here: https://travis-ci.org/mixonic/ranked-model/jobs/492525209

The full error message is:

`Gem::LoadError:
  Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).`

This only occurred after upgrading (accidentally) to 1.4.x. I've reversed this down to 1.3.x and the tests are running successfully again now. Any ideas on what could be going wrong? Perhaps the gem is failing to compile in the travis environment? I don't see any errors in the bundle process though.

**Comment by brendon** [comment]
It can also be evidenced here: https://travis-ci.org/swanandp/acts_as_list/jobs/492517389

**Comment by barrywoolgar** [comment]
Hello, this was determined to be a Rails issue - see https://github.com/rails/rails/issues/35161 referenced in #247

You just need to update your Gemfile to say `gem 'sqlite3', '1.3.13'` and you'll be sorted.

**Comment by brendon** [comment]
Thanks, yes that's what I ended up doing for both projects. Hopefully this thread helps people searching for the error message as all my searching turned up nothing easily identifiable as the problem, it was only on a whim that I downgraded the gem to see that it all worked again. :)

**Comment by obfuscoder** [comment]
Sorry for posting on this already closed issue, but we are still using Rails 4.2.x in a lot of our projects and will not be able to update anytime soon. There is no change in rails 4.x for this and it does not look like that there will be any.

So we would need to set a version constraint on the sqlite3 dependency to < 1.4.0 for all those projects? For how long will sqlite3 1.3.x be maintained?
