### ISSUE TITLE
Version 1.4 broken on Windows

### ISSUE THREAD

**Issue by sroller** [sparklemotion/sqlite3-ruby#250]
Environment: Windows 10, msys2, ruby 2.5.3p105 x64

When I install the gem version 1.4 the installation fails with a link error: can't find dlopen().
I reverted to version 1.3.11 of the gem and things where fine.
Let me know what additional information you need.

**Comment by MSP-Greg** [comment]
Try adding the mingw-w64-x86_64-dlfcn package, then running `gem install`.

I think:
```
ridk exec pacman -S mingw-w64-x86_64-dlfcn
```

**Comment by sroller** [comment]
Yes, that worked. We should change the comment in the README.md of the rubyinstaller2 project to reflect on this change.

**Comment by MSP-Greg** [comment]
Glad that helped.  I think that 'dlfcn' should be added to:

https://github.com/sparklemotion/sqlite3-ruby/blob/5c36dbeb8f61a13423d233380047d8051b7eefb7/sqlite3.gemspec#L10

and/or the following should be modified when building on Windows:

https://github.com/sparklemotion/sqlite3-ruby/blob/5c36dbeb8f61a13423d233380047d8051b7eefb7/ext/sqlite3/extconf.rb#L67-L71

haven't had a chance to look into it...
