### ISSUE TITLE
Please activate Appveyor CI on this project

### ISSUE THREAD

**Issue by larskanis** [sparklemotion/sqlite3-ruby#255]
This would prevent breaking Windows build by accident like here: https://github.com/sparklemotion/sqlite3-ruby/commit/f4ffec281a2888c1e536662ac1ea740fd3f5433c

I think @MSP-Greg and me can help to keep `appveyor.yml` up-to-date.

**Comment by flavorjones** [comment]
I'll do this as part of the refresh of native gems in #320

**Comment by flavorjones** [comment]
See #320 for a commit configuring appveyor
