### ISSUE TITLE
So embarrassing for new user to bump into error

### ISSUE THREAD

**Issue by zzz6519003** [sparklemotion/sqlite3-ruby#258]
2019-03-24 20:26:10 +0800: Rack app error handling request { GET / }
#<LoadError: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.>

cc: @tenderlove

**Comment by stomar** [comment]
See rails/rails#35551.
