### ISSUE TITLE
What version is master?

### ISSUE THREAD

**Issue by MSP-Greg** [sparklemotion/sqlite3-ruby#262]
Given that bundler allows use of repos, what version is master?

https://github.com/sparklemotion/sqlite3-ruby/blob/b6a9d731c2004d96e6b458c661d156b6a94a4f58/lib/sqlite3/version.rb#L1-L16

https://github.com/sparklemotion/sqlite3-ruby/blob/b6a9d731c2004d96e6b458c661d156b6a94a4f58/sqlite3.gemspec#L1-L7

**Comment by mishina2228** [comment]
It's similar with #303.
@flavorjones  It will be resolved when v1.4.3 is released, right?

**Comment by MSP-Greg** [comment]
This can be closed… See https://github.com/sparklemotion/sqlite3-ruby/issues/303#issuecomment-1137884977
