### ISSUE TITLE
why not publish prebuild gem with mingw and so on

### ISSUE THREAD

**Issue by WoolenWang** [sparklemotion/sqlite3-ruby#265]
after 1.3.13  the sqlite3 require user to build there gem in the target platform like windows mingw32, why not publish the prebuild version?

**Comment by MSP-Greg** [comment]
Building a 64 bit MinGW gem for Ruby 2.2 thru trunk and then testing it with each Ruby version just took 6:40 on Appveyor.

See

https://ci.appveyor.com/project/MSP-Greg/sqlite3-ruby/builds/24787784
