### ISSUE TITLE
Sqlite3 version installed with gem?

### ISSUE THREAD

**Issue by sterankin** [sparklemotion/sqlite3-ruby#274]
Strange issue I am facing with our rails project (ruby 2.4.6).
sqlite3 gem version 1.3.11.

I have rspec tests which pass locally, but they fail on the CI build.  Since we are using the same ruby version and the same sqlite3 gem version, I was at a loss as to what the issue could be.

I noticed when adding the following code to my tests:

```
sql_version= ActiveRecord::Base.connection.execute("select sqlite_version();")
      puts "SQL version is " + sql_version.first.to_s
```

The sql version on my local machine was: `{"sqlite_version()"=>"3.29.0", 0=>"3.29.0"}`

But on the CI server the same code reveals:  `{"sqlite_version()"=>"3.7.17", 0=>"3.7.17"}`

Could this be the cause if my failing specs?

`SQLite3::SQLException: near "WITH": syntax error: ;WITH included_items as (`

My next step is to try an replicate this locally, but how can I force the sqlite3 gem to use an older version of sqlite3?

Why would the CI server report a different version of sqlite3 when the exact same gem is installed?

**Comment by tenderlove** [comment]
The gem is only a wrapper around libsqlite3.  You have libsqlite3 version 3.29.0 installed locally and 3.7.19 installed on CI.  You'll need to install a different version of libsqlite3 (which is a different thing than the gem).  I hope that helps!

**Comment by sterankin** [comment]
Cheers Aaron , I solved this by using Docker on my CI build to ensure the correct versions were installed.
