### ISSUE TITLE
Special dot-commands

### ISSUE THREAD

**Issue by Shoroh** [sparklemotion/sqlite3-ruby#290]
Hey!

I'm not sure if it's a bug or a lack of docs, or there is no feature like this one at all.
How can I use such commands with this interface?

- .separator
- .import
- .mode csv
- .stats
etc.

I got this error: 
near ".": syntax error

**Comment by Shoroh** [comment]
Looks like I seethe reason :)

> The dot-commands are interpreted by the sqlite3.exe command-line program, not by SQLite itself. So none of the dot-commands will work as an argument to SQLite interfaces like sqlite3_prepare() or sqlite3_exec().

It's a pity that we can't import a whole CSV file with millions of records from Ruby app within a couple of seconds using two lines :(

**Comment by jedschneider** [comment]
Would it be possible to start the sqlite session with the same flags you provide the the cli executable? Then you can do things this:

```
% sqlite3 -json test.db
SQLite version 3.37.0 2021-12-09 01:34:53
Enter ".help" for usage hints.
sqlite> select * from connections limit 1;
[{"user_one":"xxx","user_two":"yyy"}]
sqlite>
```
