### ISSUE TITLE
mismatch between gemspec version and rubygems.org

### ISSUE THREAD

**Issue by vtcifer** [sparklemotion/sqlite3-ruby#303]
There have been 3 versions published to rubygems.org (1.4.0, 1.4.1, 1.4.2) since 1.3.13 (which is the current listed version in the gemspec here).  Was updating the gemspec just missed?

**Comment by flavorjones** [comment]
The gemspec is automatically generated from the Hoe spec in the Rakefile, and was not updated.

It will be updated for the upcoming 1.4.3 release.
