### ISSUE TITLE
Time/ DateTime support?

### ISSUE THREAD

**Issue by rongcuid** [sparklemotion/sqlite3-ruby#338]
It would be great if binding `Time` and `DateTime` is supported:

```
in `bind_param': can't prepare DateTime (RuntimeError)
```

```
in `bind_param': can't prepare Time (RuntimeError)
```

**Comment by flavorjones** [comment]
Hello @rongcuid! Thanks for opening this issue.

It might be good to know that type translation is available during reads if you turn type translation on:

``` ruby
#! /usr/bin/env ruby

require "bundler/inline"

$VERBOSE = false

gemfile do
  source "https://rubygems.org"
  gem "sqlite3"
end

require "sqlite3"
require "time"

db = SQLite3::Database.new(":memory:")
db.type_translation = true
db.execute("create table foo(name TEXT, created_at DATETIME, born_on DATE);")
db.execute("insert into foo values ('raw insertion', datetime('now'), date('now'));")

db.execute("select * from foo") # => [["raw insertion", #<DateTime: 2022-08-26T16:27:32+00:00 ((2459818j,59252s,0n),+0s,2299161j)>, #<Date: 2022-08-26 ((2459818j,0s,0n),+0s,2299161j)>]]
```

but yes, you're right, type translation is not done during insertions or updates as noted in the [`SQLite3::Database` docstring](https://www.rubydoc.info/github/sparklemotion/sqlite3-ruby/master/SQLite3/Database):

> The Database class provides type translation services as well, by which the SQLite3 data types (which are all represented as strings) may be converted into their corresponding types (as defined in the schemas for their tables). This translation only occurs when querying data from the database–insertions and updates are all still typeless.

Maybe @tenderlove can share his thinking around the type translation feature? It looks like it's been deprecated and I'm not familiar with whether it will continue to be supported.

**Comment by tenderlove** [comment]
I'd like the SQLite gem to be just a wrapper around the SQLite library itself. SQLite [has very few data types](https://www.sqlite.org/datatype3.html), and the built-in date time functions [support many different formats](https://www.sqlite.org/lang_datefunc.html).

I don't think this gem should be opinionated about how dates / times are formatted in the database as our opinions could work for some people but not for other people.

**Comment by npapagna** [comment]
Is this feature going to be moved to, say, the `SQLite3Adapter` in Rails?
