### ISSUE TITLE
Execute the same statement in batch with different parameters

### ISSUE THREAD

**Issue by collimarco** [sparklemotion/sqlite3-ruby#344]
I would like to use something like this:

```
items = [[1, 'foo'], [2, 'bar'], [3, 'xyz']]
db.execute_batch("INSERT INTO items (id, name) VALUES (?, ?)", items)
```

However that doesn't work.

What is the correct way to execute a batch insert with this gem (same statement, different params)?

**Comment by flavorjones** [comment]
I think this is answered in [the FAQ question about prepared statements](https://github.com/sparklemotion/sqlite3-ruby/blob/master/faq/faq.md#how-do-i-prepare-a-statement-for-repeated-execution) and subsequent questions about binding parameters.

Please let us know if you think that section needs to be clarified?

**Comment by flavorjones** [comment]
Ah, I misunderstood the question. Reopening.

**Comment by flavorjones** [comment]
The `#execute_batch` and `#execute_batch2` methods execute a batch of SQL statements, though I appreciate the name might imply "run this SQL statement for this batch of parameters".

I'm a relatively new maintainer and so someone may wish to correct me, but I believe the current API only allows you to prepare a statement, and then loop through your parameters calling `#execute` once each. There's no shortcut for ripping through a batch of statement parameters.
