### ISSUE TITLE
Can't install on Ruby 2.3 though gemspec state Ruby 1.9

### ISSUE THREAD

**Issue by Nakilon** [sparklemotion/sqlite3-ruby#359]
The gemspec say:

```ruby
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.2")
```

But:

```none
$ gem install sqlite3
Fetching: sqlite3-1.5.3-x86_64-darwin.gem (100%)
ERROR:  Error installing sqlite3:
	sqlite3 requires Ruby version < 3.2.dev, >= 2.6.
$ ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin18]
```

Where is the `>= 2.6` specified?

MacOS

**Comment by flavorjones** [comment]
Hi, the precompiled native gems will only support specific versions of Ruby, and the gemspec shipped with them says this. See for example https://rubygems.org/gems/sqlite3/versions/1.5.3-x86_64-darwin

If you upgrade rubygems and/or bundler, modern versions are able to understand these limitations and choose the right version.

Or, you may want to consider upgrading your version of Ruby, 2.3 has been EOL for several years now.

**Comment by Nakilon** [comment]
Oh, I'm sorry for not spotting the `--platform=ruby` in README.

Though it's just hanging now for several minutes for me:

```none
$ gem install sqlite3 --platform=ruby

```

**Comment by flavorjones** [comment]
If you want to build against system libraries, that will be faster. The instructions are also in the README, but in summary:

```
gem install sqlite3 -- --enable-system-libraries
```
