### ISSUE TITLE
No discussion open for 1.6.0.rc2 release

### ISSUE THREAD

**Issue by gwillcox-r7** [sparklemotion/sqlite3-ruby#373]
Hi there, I see [1.6.0.rc2](https://github.com/sparklemotion/sqlite3-ruby/releases/tag/v1.6.0.rc2) has a tag, but there is no discussion open for it, so people aren't able to leave feedback on if it works on MacOS for them or not. Would it be possible to make a discussion section for this release so people can leave feedback on your  approach to Darwin symbol resolution in the precompiled extension and help ensure its working for everyone?

**Comment by flavorjones** [comment]
Yeah, sorry about that.
