### ISSUE TITLE
sqlite 3.43.0 AVG() is broken with respect to dealing with Infinities

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/sqlite3-ruby#396]
The Rails team reported that builds are failing with sqlite3-ruby v1.6.4 native gems.

https://buildkite.com/rails/rails-ci/builds/96#018a3420-d15c-41fc-8d05-7cb688942050

Upstream definitely changed how floats were handled, so I'm digging in to bisect and diagnose the issue.

**Comment by flavorjones** [comment]
The test that's failing is

```

Failure:
  | CalculationsTest#test_should_return_float_average_if_db_returns_such [/rails/activerecord/test/cases/calculations_test.rb:83]:
  | Expected: Infinity
  | Actual: nil
  |  
  |  
  | bin/rails test /rails/activerecord/test/cases/calculations_test.rb:72
 ```

Trying to reproduce this on my development machine. First pass did not repro, but I have a hunch (after peeking at the sqlite commit log) that float behavior changed in compiler- or hardware-specific ways.

**Comment by flavorjones** [comment]
Reproduced on my development machine. Going to bisect upstream.

**Comment by flavorjones** [comment]
Running git-bisect points at this upstream commit as introducing the new behavior: https://github.com/sqlite/sqlite/commit/45d7562843ed1aaaa24666591cea8452110fd917

**Comment by flavorjones** [comment]
OK, I'm going to try to isolate this issue, I'm not very familiar with how `Infinity` is handled in the active record / arel / sqlite3-ruby / sqlite stack so I need to do some learning and then figure out if this is a bug in sqlite and/or whether we can work around it.

**Comment by flavorjones** [comment]
OK, narrowed down to this test case:

```ruby
  def test_raw_float_infinity
    db = SQLite3::Database.new ":memory:"
    db.execute("create table foo (temperature float)")
    db.execute("insert into foo values (?)", 37.5)
    db.execute("insert into foo values (?)", Float::INFINITY)
    assert_equal Float::INFINITY, db.execute("select avg(temperature) from foo").first.first
  end
```

which fails when run against 45d75628 but passes when run against any earlier commit.

I'm going to report this upstream. In the meantime, anybody who's depending on this behavior should probably not use sqlite 3.43.0.

**Comment by flavorjones** [comment]
SQL to reproduce this:

```sql
create table foo (bar float);
insert into foo values (37.5);
insert into foo values (1e10000);
select avg(bar) from foo;
```

**Comment by flavorjones** [comment]
Reported upstream (on the public forum per the [project protocol](https://www.sqlite.org/src/wiki?name=Bug+Reports)): https://www.sqlite.org/forum/forumpost/1c06ddcacc

**Comment by flavorjones** [comment]
This was fixed upstream on trunk, waiting for a new release.

**Comment by flavorjones** [comment]
Upstream v3.43.1 has been released with a fix, I'll cut a release as soon as I can.

**Comment by voxik** [comment]
> Upstream v3.43.1 has been released with a fix, I'll cut a release as soon as I can.

[SQLite 3.43.1](https://sqlite.org/releaselog/3_43_1.html) fixes this according to my testing and resolves rails/rails/issues/49169 for me

**Comment by flavorjones** [comment]
Welp, I was hoping for the best but am unsurprised by this still being an incomplete fix: see https://github.com/sparklemotion/sqlite3-ruby/pull/406 failing on windows and macos builds.

**Comment by flavorjones** [comment]
[Release 1.6.6 / 2023-09-12 · sparklemotion/sqlite3-ruby](https://github.com/sparklemotion/sqlite3-ruby/releases/tag/v1.6.6) is out
