### ISSUE TITLE
Allow passing sqlite CFLAGS via a extconf.rb argument that is configurable by bundler

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/sqlite3-ruby#401]
See #400 for the discussion that ended with this feature request.

The user in this case is someone who is a sqlite professional™ and wants to set some compile-time flags for default pragma values. See https://fractaledmind.github.io/2023/09/07/enhancing-rails-sqlite-fine-tuning/ for an example use case.

Currently the only way to do this is to set a CFLAGS environment variable at gem installation time (and, separately, to ensure that you download and compile the source gem, not a precompiled gem).

It would be helpful if options were all contained within the bundler/gemfile toolchain, so that these two changes would be sufficient:

```ruby
# Gemfile
gem "sqlite3", force_ruby_platform: true # needs bundler 2.3.18 or higher
```

And a bundler config:

```
bundle config build.sqlite3 --sqlite-cflags="-DSQLITE_DEFAULT_PAGE_SIZE=16300"
```

(or the equivalent entry in `.bundler/config`:

```
BUNDLE_BUILD__SQLITE3: "--sqlite-cflags=-DSQLITE_DEFAULT_PAGE_SIZE=16300"
```

**Comment by fractaledmind** [comment]
One small note for the issue, you copy/pasted Bundler config values for Nokogiri. 

That typo aside, I think this could be an amazing feature, and whatever I can do to help or test, I'm down

**Comment by flavorjones** [comment]
LOL! Fixed the nokogiri paste error.

**Comment by flavorjones** [comment]
PR up at #402
