### ISSUE TITLE
prep for v2.0

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/sqlite3-ruby#450]
After a chat with @tenderlove today, we're going to start preparing for a 2.0 release.

Punchlist:

- [x] update default branch to `main`
- [x] bump version to 2.0.0.dev - dc4c05c4
- [x] format C code to CRuby standard - https://github.com/sparklemotion/sqlite3-ruby/pull/452
- [x] remove deprecated functionality
  - [x] VersionProxy https://github.com/sparklemotion/sqlite3-ruby/pull/453
  - [x] type translation #470
  - [x] Row array wrappers #471 
  - [x] Deprecated method signature support #511
- [x] drop Ruby 2.7 support - https://github.com/sparklemotion/sqlite3-ruby/pull/453
- [x] format Ruby code https://github.com/sparklemotion/sqlite3-ruby/pull/467
- [x] doc file cleanup: https://github.com/sparklemotion/sqlite3-ruby/pull/494
- [x] add required builds so that we can take advantage of "automerge"
- [x] Better Ractor support
  -  ~#365~ - after discussion we won't block a release on that work
  - [x] feature: deeply freeze result rows (freeze strings / array). This will better support Ractor producer / consumer patterns https://github.com/sparklemotion/sqlite3-ruby/pull/480
- [x] improve ci
  - [x] refactor existing tests https://github.com/sparklemotion/sqlite3-ruby/pull/479
  - [x] add downstream integration test against Active Record https://github.com/sparklemotion/sqlite3-ruby/pull/491
- [x] investigate https://github.com/sparklemotion/sqlite3-ruby/issues/489
- [x] first-class musl support: https://github.com/sparklemotion/sqlite3-ruby/pull/442 (blocked on rubygems)

**Comment by tenderlove** [comment]
Great!! 🎉

**Comment by flavorjones** [comment]
@tenderlove is there anything remaining to do for "Deprecated method signature support"? I'm not entirely sure I understand what that's referring to.

musl support is, I think, the remaining big blocker, that was blocked on a rubygems issue solved (but not yet released) in https://github.com/rubygems/rubygems/pull/7441 and that we need to document. hoping to get through it this week.

**Comment by flavorjones** [comment]
Closing the loop:
- "deprecated method signature" look for the `$VERBOSE` warnings
- for ractor support, we won't block on #365 but @tenderlove is open to continuing that work and improving ractor support in a minor release
- musl support is unblocked

I've updated the punchlist.

**Comment by flavorjones** [comment]
I wrote a script that will add all recent CI jobs to the "required status checks" for `main`. Will probably clean it up at some point, but in the meantime just ask me if we need to adjust the checks, since doing it manually is quite annoying.

**Comment by flavorjones** [comment]
OK, all the punchlist items are done. I'm planning to cut a release candidate tomorrow.

**Comment by flavorjones** [comment]
Done!

**Comment by flavorjones** [comment]
https://github.com/sparklemotion/sqlite3-ruby/releases/tag/v2.0.0
