### ISSUE TITLE
Inconsistent required ruby version

### ISSUE THREAD

**Issue by JonRowe** [sparklemotion/sqlite3-ruby#487]
Hello! Thanks for the work on this project, I wanted to bring to your attention an issue with the required version of Ruby in the various releases, the headline 1.7.1 [which rubygems defaults to displaying] has support for Ruby 2.7, whilst the ARM version is 3.0 plus, this causes bundler to not be able to resolve a working versions for Ruby 2.7. I'd suggest either relaxing this back down to 2.7, or at least being consistent across all versions [this is also a breaking change under semantic versioning IMO].

**Comment by flavorjones** [comment]
@JonRowe Thanks for asking this question.

In the [changelog entry for 1.7.0](https://github.com/sparklemotion/sqlite3-ruby/blob/main/CHANGELOG.md#170--2023-12-27) we noted that the precompiled native gems will only ship binaries for Ruby 3.0 and later; but that the source gem still supports 2.7. So what you're seeing is intended behavior.

If you can give us more information about what your Gemfile and Gemfile.lock contain I might be able to help you configure your project. But generally my advice would be to make sure bundler is updated to the most recent version supported by your Ruby, and/or pin to a version of sqlite3-ruby that works for your platform and ruby version.

> this is also a breaking change under semantic versioning IMO

SemVer says this is a compatible change as long as the public API isn't affected: https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api :shrug:

**Comment by JonRowe** [comment]
Hi I don't need help configuring my project, I came across this whilst attempting to release rspec-rails as my machine is an M1 Pro and I happened to be on 2.7.8 at the time from testing something.

I still disagree with your interpretation of semver as the version of Ruby is not the same as some other dependency and bundler can't figure this out automatically, in my opinion you should at least make all the versions consitent so that bundler will ignore this version on 2.7.x

**Comment by flavorjones** [comment]
> in my opinion you should at least make all the versions consitent so that bundler will ignore this version on 2.7.x

bundler _should_ be able to figure out how to resolve the scenario you're describing. If it's not working for you, I think that a bug report should be opened with bundler.

**Comment by flavorjones** [comment]
Note that rubygems 3.4.22 (maybe an earlier release) seems to have fixed the bug described above, which is another way to work around this problem.
