### ISSUE TITLE
Fix GitHub license field

### ISSUE THREAD

**Issue by tenderlove** [sparklemotion/sqlite3-ruby#499]
GitHub doesn't seem to understand what the license is:

<img width="354" alt="sparklemotion:sqlite3-ruby: Ruby bindings for the SQLite3 embedded database 2024-02-02 09-52-23" src="https://github.com/sparklemotion/sqlite3-ruby/assets/3124/e2760669-dfec-44cf-8d14-763e3768b961">

I didn't recognize [the license file](https://github.com/sparklemotion/sqlite3-ruby/blob/a313b9a7dbcbae06d39282620e70a03f4ab6c61a/LICENSE) either, but it's actually the [3-Clause BSD license](https://opensource.org/license/bsd-3-clause/).

I don't think we should change the license, but there must be a way to get GitHub to display the right thing. We probably should update the copyright year and also add "et, al." to the license as well.

**Comment by flavorjones** [comment]
This is weird, licensee seems to detect it fine:

```
$ licensee
License:        NOASSERTION
Matched files:  LICENSE, LICENSE-DEPENDENCIES, README.md, sqlite3.gemspec
LICENSE:
  Content hash:  9af635d4936231a9dcddc9fb82fda06054549710
  Attribution:   Copyright (c) 2004, Jamis Buck (jamis@jamisbuck.org)
  Confidence:    98.72%
  Matcher:       Licensee::Matchers::Dice
  License:       BSD-3-Clause
  Closest non-matching licenses:
    BSD-3-Clause similarity:  98.72%
    BSD-4-Clause similarity:  82.44%
    BSD-2-Clause similarity:  81.75%
LICENSE-DEPENDENCIES:
  Content hash:  ff81633c53aece3489d4541bdc15ab5a5c6a8938
  License:       NOASSERTION
  Closest non-matching licenses:
    ISC similarity:         20.14%
    Zlib similarity:        19.05%
    PostgreSQL similarity:  14.43%
README.md:
  Content hash:  48a9b510f0fb871de54d6b0cb0eef7226d8bcaef
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       BSD-3-Clause
  Closest non-matching licenses:
    WTFPL similarity:  5.66%
    0BSD similarity:   1.94%
    ISC similarity:    1.72%
sqlite3.gemspec:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::Gemspec
  License:     BSD-3-Clause
```

**Comment by flavorjones** [comment]
see #501
