### ISSUE TITLE
Version 1.7.3 is not working anymore for recent Apple ARM architectures

### ISSUE THREAD

**Issue by Victorcorcos** [sparklemotion/sqlite3-ruby#547]
It looks like the `1.7.3` version is not working while the `1.4.2` version is working for my machine. 
Does anyone have an idea about how to fix this?

## Version `1.7.3` (latest) not working

```rb
$ sudo gem install sqlite3 -v '1.7.3' --source 'https://rubygems.org/' -- --with-cflags="-Wno-error=int-conversion -Wno-error=incompatible-function-pointer-types"
ERROR:  Error installing sqlite3:
	The last version of sqlite3 (= 1.7.3) to support your Ruby & RubyGems was 1.7.3. Try installing it with `gem install sqlite3 -v 1.7.3` and then running the current command again
	sqlite3 requires Ruby version >= 3.0, < 3.4.dev. The current ruby version is 2.7.8.225.
```

I tried to install by the recommended code (`gem install sqlite3 -v 1.7.3`), but it still doesn't work and the exact same error appears.

## Version `1.4.2` working

```rb
$ sudo gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/' -- --with-cflags="-Wno-error=int-conversion -Wno-error=incompatible-function-pointer-types"

Building native extensions with: '--with-cflags=-Wno-error=int-conversion -Wno-error=incompatible-function-pointer-types'
This could take a while...
Successfully installed sqlite3-1.4.2
Parsing documentation for sqlite3-1.4.2
Installing ri documentation for sqlite3-1.4.2
Done installing documentation for sqlite3 after 0 seconds
1 gem installed
```

## My Configs

I have a MacBook Pro M3 Max with the Sonoma 14.5 operating system.

![letschange](https://github.com/sparklemotion/sqlite3-ruby/assets/7637806/a3196063-914d-465f-86ca-9a3c3232ec92)

**Comment by Uepsilon** [comment]
I'm running into the same issue, so what's the solution here and why does it happen? 🤔

**Comment by flavorjones** [comment]
@Uepsilon Please open a new issue if you're having problems.
