### ISSUE TITLE
Unable to install sqlite3  for Ruby2.0.0 on Windows 7

### ISSUE THREAD

**Issue by yuumi3** [sparklemotion/sqlite3-ruby#82]
```
C:\Ruby200\DevKit>gem install sqlite3
Fetching: sqlite3-1.3.7.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    C:/Ruby200/bin/ruby.exe extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include

          ….

        --without-sqlite3-lib=${sqlite3-dir}/
        --enable-local
        --disable-local


Gem files will remain installed in C:/Ruby200/lib/ruby/gems/2.0.0/gems/sqlite3-1
.3.7 for inspection.
Results logged to C:/Ruby200/lib/ruby/gems/2.0.0/gems/sqlite3-1.3.7/ext/sqlite3/
gem_make.out
```

and

```
C:\Ruby200\DevKit>gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.0
  - RUBY VERSION: 2.0.0 (2013-02-24 patchlevel 0) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby200/lib/ruby/gems/2.0.0
  - RUBY EXECUTABLE: C:/Ruby200/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby200/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/Ruby200/lib/ruby/gems/2.0.0
     - C:/Users/yy/.gem/ruby/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/
```

**Comment by ALiiEN** [comment]
Im getting this proglem. 

$ gem install sqlite3 --platform=ruby -- --with-sqlite3-include=path_to_include --with-sqlite3-lib=path_to_lib --with-sqlite3-dir=path_t
o_dll
Building native extensions with: '--with-sqlite3-include=path_to_include --with-sqlite3-lib=path_to_lib --with-sqlite3-dir=path_to_dll'
This could take a while...
C:/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/ext/ext_conf_builder.rb:39: warning: Tempfile#unlink or delete called on open file; ignoring
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    C:/jruby-9.0.0.0/bin/jruby.exe -r ./siteconf20151208-24888-1kbf9cg.rb extconf.rb --with-sqlite3-include=path_to_include --with-sqlite3-lib=path_to_lib --with-sqlite3-dir=path_to_dll
NotImplementedError: C extensions are not supported
    <top> at C:/jruby-9.0.0.0/lib/ruby/stdlib/mkmf.rb:1
  require at org/jruby/RubyKernel.java:940
   (root) at C:/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
    <top> at extconf.rb:3

extconf failed, exit code 1

Gem files will remain installed in C:/jruby-9.0.0.0/lib/ruby/gems/shared/gems/sqlite3-1.3.11 for inspection.
Results logged to C:/jruby-9.0.0.0/lib/ruby/gems/shared/extensions/universal-java-1.8/2.2.0/sqlite3-1.3.11/gem_make.out

**Comment by luislavena** [comment]
Hello,

JRuby does not support Center extensions, which is being informed in the
error message:

NotImplementedError: C extensions are not supported

sqlite3-ruby links to libsqlite3 using a V extension.

You need to use instead jdbc-sqlite or similar. I don't know JRuby and the
Java ecosystem to provide you further guidance.

Sorry for top posting, sent from mobile.
