### ISSUE TITLE
Installing 1.3.7 on FreeBSD 9.1 with RVM and Ruby 2.0.0

### ISSUE THREAD

**Issue by ghost** [sparklemotion/sqlite3-ruby#83]
Hi, I'm getting errors trying to install on FreeBSD 9.1 with RVM and Ruby 2.0.0.

I first tried:

gem install sqlite3

Building native extensions.  This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

```
/home/oggy/.rvm/rubies/ruby-2.0.0-p0/bin/ruby extconf.rb
```

checking for sqlite3.h... no
sqlite3.h is missing. Try 'port install sqlite3 +universal'

Then tried adding the --with-sqlite3-dir=/usr/local option as suggested online:

gem install sqlite3 -- --with-sqlite3-dir=/usr/local

Building native extensions with: '--with-sqlite3-dir=/usr/local'
This could take a while...ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

```
/home/oggy/.rvm/rubies/ruby-2.0.0-p0/bin/ruby extconf.rb --with-sqlite3-dir=/usr/local
```

checking for sqlite3.h... yes
checking for sqlite3_libversion_number()... -lsqlite3
sqlite3 is missing. Try 'port install sqlite3 +universal'or 'yum install sqlite-devel' and check your shared library search path (the
location where your sqlite3 shared library is located).**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/oggy/.rvm/rubies/ruby-2.0.0-p0/bin/ruby
        --with-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/
        --enable-local
        --disable-local
        --with-sqlite3lib
        --without-sqlite3lib

Gem files will remain installed in /home/oggy/.rvm/gems/ruby-2.0.0-p0/gems/sqlite3-1.3.7 for inspection.
Results logged to /home/oggy/.rvm/gems/ruby-2.0.0-p0/gems/sqlite3-1.3.7/ext/sqlite3/gem_make.out

I have sqlite3 installed from ports:

whereis sqlite3

sqlite3: /usr/local/bin/sqlite3

Any help would be great.

Thanks

**Comment by graudeejs** [comment]
@danielb2, @luislavena   +1, 

doing ```gem install sqlite3 -- --with-opt-dir=/usr/local``` manually every time I need sqlite gem is really frustrating.

**Comment by sebi** [comment]
Please reopen this issue. It's still present on FreeBSD 10.2 and it's really frustrating.
