### ISSUE TITLE
Is output tainted?

### ISSUE THREAD

**Issue by bastilian** [sparklemotion/sqlite3-ruby#94]
When i use sqlite3 in combination with safe_erb (https://github.com/abedra/safe-erb) in Mephisto (https://github.com/bastilian/mephisto) i get several issues telling me that output from sqlite3 is not tainted, when using other db-adapters everything works like a charm.

I did my research and found that in fact sqlite3 should taint output, can anyone verify this, so i can rule it out as the cause?

Thanks,
Sebastian

**Comment by tenderlove** [comment]
Closing this issue because it looks stale.  If it's not, please comment.  Thanks!
